### ISSUE TITLE
Inverse Square Root Algorithm

### ISSUE THREAD

**Issue by ErdemT09** [spiralgo/algorithms#1]
Here is an algorithm that approximates the inverse and normal square root of a number using floating-point bit manipulation and Newton's method: https://github.com/ErdemT09/Fast-inverse-square-root/blob/master/FastInverseSqrt.java

**Comment by altayhunoglu** [comment]
Thank you Erdem.

**Comment by altayhunoglu** [comment]
As it is solved...
