### ISSUE TITLE
582. Kill Process

### ISSUE THREAD

**Issue by altayhunoglu** [spiralgo/algorithms#10]
https://leetcode.com/problems/kill-process/

Burada process'i, bir bilgisayarda çalışmakta olan bir işlem olarak düşünebiliriz.
Bazen işlemler, alt-işlemlerden oluşuyor. 
Bu soruda da, aynı şekilde "process" (işlem) ve "parent process" (ana-işlem) kavramı var.

Bir işlemin yalnızca bir tane parent işlemi olabilir. Ama birden fazla yavrusu olabilir.
Bize iki liste veriliyor.

List<Integer> pid:
İşlemleri içeren liste. Buradaki her bir eleman, o anki indeks ile gösterilen bir işlemin ID'sini içerir.
 List<Integer> ppid: Buradaki her bir eleman, o anki index ile gösterilen bir işlemin "parent" işleminin id'sini gösterir.

Bizden istenen ise, bir işlem sonlandırıldığında, o işlemin tüm yavruları ile birlikte sonlandırılmasını sağlamak.

Sonlandırılan işlemlerin ID'lerinin listesini de gene bir liste ( List<Integer>) olarak return ile döndürmemiz isteniyor.

**Comment by ErdemT09** [comment]
Solved:
https://github.com/spiralgo/algorithms/tree/master/src/main/java/algorithms/curated170/medium/killprocess
