### ISSUE TITLE
300. Longest Increasing Subsequence

### ISSUE THREAD

**Issue by altayhunoglu** [spiralgo/algorithms#101]
(Teknik açıklama (*) en aşağıdadır.)

Bu soruyu en küçük birimlerden başlayarak ("bottom-up") ele almak daha açık bir çözüm olur. 
Bu arrayi ele alalım:
 nums = [1,2,3,7,4,5,8]

Arrayin ilk elemanını düşünelim.
nums[0] = 1. 
Bu elemandan önce hiçbir eleman gelmiyor. Demek ki, nums arrayi bu elemandan ibâret olsa idi sorunun cevâbı 1 olurdu.
nums[1] = 2 elemanı için ise cevap 2 olurdu. Çünkü, kendisi ile birlikte nums[0]'ın cevâbını da içermiş oluyor.

En doğrusu şöyle düşünmektir. Biz herhangi bir elemana kadar olan kısımdaki "Longest Increasing Subsequence" uzunluğuna
o elemanın "**gücü**" diyelim.

Belki şöyle genel bir formülden bahsetmek yanlış olmayacaktır:

_"Bir elemanın **gücü**, kendisinden önce gelen (daha küçük) sayılardan en güçlüsünün (**previousMostPowerful**) gücünü de içerir. Kendisinden de 1 ekler."_

Demek ki her bir elemanı gezeceğiz ve her bir eleman için kendisinden küçükleri bulacağız. Bu küçükler arasında en güçlü olanın gücünü emeceğiz. Soru bize, eninde sonunda en güçlü olanı sormuş olur. (**theMostPowerful**)

```
public class Solution {
    public int lengthOfLIS(int[] nums) {
        if (nums.length == 0) {
            return 0;
        }
        int[] currentElementPower = new int[nums.length];
        currentElementPower[0] = 1;
        int theMostPowerful = 1;
        for (int i = 1; i < currentElementPower.length; i++) {
            int previousMostPowerful = 0;
            for (int j = 0; j < i; j++) {
                if (nums[i] > nums[j]) {
           previousMostPowerful = Math.max(previousMostPowerful, currentElementPower[j]);
                }
            }
            currentElementPower[i] = previousMostPowerful + 1;
            theMostPowerful = Math.max(theMostPowerful, currentElementPower[i]);
        }
        return theMostPowerful;
    }
}
```

 

*:
Longest = en uzun
Increasing = artan sıralı
Subsequence = array'in, aynı doğrultudaki bir parçası. Aynı doğrultuda, yani karakterlerin yerleri değişmiyor. Ancak karakterler arasında boşluk olabilir.

 Mesela: [1, 2, 3]  integer arrayi için; [1, 2] bir subsequence olduğu gibi; [1, 3] de bir subsequencetir. Ancak [2, 1] bir subsequence değildir.

**Comment by ErdemT09** [comment]
Bu çözümde array'in her öğesi kendinden önceki öğelerin hepsiyle karşılaştırılıyor. Bu bize array'in array uzunluğuna kadar olan sayıların toplamı gibi bir işlem verir, bu O(n^2)'ye karşılık gelir. Bu bazı gerekmeyen işlemlere yol açacaktır:
Input: [9, 8, 7, 5, 4, 1, 2, 3]
İşlemler:  4 sayısına kadar LIS'ın ilk sayısını değiştirmekten başka bir işlem yapmadığımız hâlde her öğede kendinden önceki tüm öğelerin LIS'ını uzatıp uzatamayacağına bakıyoruz. Belki bunu yapmak yerine ana LIS'ı kaydedip, onla karşılaştırabiliriz. 
LIS'ı kaydederek işlemler:  Eğer elimizdeki sayı LIS'ın son öğresinden küçükse onu bunla değiştiririz. Böylece 1'e geldiğimizde LIS'taki 4'ü de birle değiştiriz. Eğer sayı büyükse ekleriz. Böylece sonda [1,2,3] şeklinde bir derlemin uzunluğu olan 3'ü döndürürüz. Öbür durumlar içinse LIS'ı tuttuğumuz array/list her zaman sorted bir derlemdir, o zaman binary search kullanabiliriz.
Örnek 2: 
Input: [0,8,4,12,2,10]
İşlemler: 
Başlangıç: 0'ı ekle: [0]
8>son öğe 0 => ekle: [0,8]
4<son öğe 8 => LIS içinde bunu koyabileceğimiz yeri bölerek ikili ara: 
while(sol!=sağ) => sol = 0, sağ = LIS.length=1; orta = (sol+sağ)/2 = 0; LIS[0] = 0 > 4; O zaman:sol = orta +1 = 1; sol=sağ, işlem biter; sol'u döndür
=> [0,4]
12>son öğe 4 => ekle: [0,4,12]
2<son öğe 12=> bölerek ara, 1 index'ini bulur: [0, 2, 12] 
Eğer 12'de bitseydi, doğrudan LIS'ı değil, uzunluğunu buluyoruz. 
10 < son öğe 12 => bölerek ara, 2 index'ini bulur: [0,2,10]; => uzunluk 3.
2'yi öyle araya yerleştirerek LIS'ın sırasını bozmamızın nedeni sonraki öğelerde olası düşük elementler için kaydetmek. Üstteki örneği değiştirelim:
Input: [0,8,4,12,2,3,10]
Eğer 4'ün yerine 2'yi koyarak sırayı bozmasaydık, 2'den sonra gelen 3 öğesini derleme ekleyemezdik. 
Bu algoritma en kötü durumda O(n log n)'e karşılık gelir. Input'u loop'lamak n, her keresinde ikili arama yapmak log n => O(n log n)

Kod1: (Buradan: https://www.geeksforgeeks.org/longest-monotonically-increasing-subsequence-size-n-log-n/)
```
class Solution {
    public int lengthOfLIS(int[] A) {
        int size = A.length;
        int[] tailTable = new int[size];
        int len; // always points empty slot
  
        tailTable[0] = A[0];
        len = 1;
        for (int i = 1; i < size; i++) {
            if (A[i] < tailTable[0])
                // new smallest value
                tailTable[0] = A[i];
  
            else if (A[i] > tailTable[len - 1])
                // A[i] wants to extend largest subsequence
                tailTable[len++] = A[i];
  
            else
                // A[i] wants to be current end candidate of an existing
                // subsequence. It will replace ceil value in tailTable
                tailTable[CeilIndex(tailTable, -1, len - 1, A[i])] = A[i];
        }
  
        return len;
    }
       static int CeilIndex(int A[], int l, int r, int key)
    {
        while (r - l > 1) {
            int m = l + (r - l) / 2;
            if (A[m] >= key)
                r = m;
            else
                l = m;
        }
  
        return r;
    }
}
```

Kod2: (Buradan: https://leetcode.com/problems/longest-increasing-subsequence/discuss/74824/JavaPython-Binary-search-O(nlogn)-time-with-explanation)
```
class Solution {
    public int lengthOfLIS(int[] nums) {
         int[] tails = new int[nums.length];
    int size = 0;
    for (int x : nums) {
        int i = 0, j = size;
        while (i != j) {
            int m = (i + j) / 2;
            if (tails[m] < x)
                i = m + 1;
            else
                j = m;
        }
        tails[i] = x;
        if (i == size) ++size;
    }
    return size;
    }
}
```

**Comment by altayhunoglu** [comment]
Selâmlar Erdem,

  Düşündüğümde vardığım karâr şu:
  
  N² çözümü **LongestIncreasingSubsequenceSlow** olarak ekleyelim.
  **Patience Sort**'a dayanan N*LogN çözümü ise **LongestIncreasingSubsequenceFast** olarak ekleyelim.
  Zannedersem, soruyu ilk defâ gören birisi eğer daha önce Patience Sort'tan haberdâr değilse, ikinci çözüme ulaşmak için çok zorlanacaktır.
  Muhtemelen önce ilki için uğraşacaktır. Görüşmeyi yapan kişi daha "efficient" bir çözüm istediğinde Patience Sort'u hatırlayan birisi gerçekten iyi iş başarmış olur. 
  Üstüne bir de kodu çıkarırsa zâten tamâmdır.
  
 
  _Konu ile dolaylı bağlantılı not:
  
 Verdiğin linkte _offline-algorithm/online-algorithm_ ayrımı yapmış. Böyle bir ayrımın sezgisel olarak farkında idim ama böyle kavramlaştırmaları güzel olmuş.
 **Online algoritma** olarak **insertion sort** örneğine bakınca ne demek istediklerini daha iyi anladım.
 Algoritmaya eklenen her elemanda dizilim değişiyor.  
 Sanki internetten dinamik olarak veri çektikçe web sayfasının değişmesi gibi olduğu için online algoritma demeleri güzel olmuş.
 Tüm inputu değil, kendisine verilen kadarını işleyen algoritma türü.
 
 **Selection Sort** ise, insertion sort’un aksine **offline**.
 Çünkü karar vermek için, tüm inputun elde bulunmasına ihtiyaç duyuyor._

**Comment by ErdemT09** [comment]
TreeSet ile de böyle bir çözümü varmış.
TreeSet'in ceiling methodu bize sayıya eşit ya da sayıdan büyük en küçük sayıyı veriyor.
Eğer böyle bir sayı varsa bunu kaldırıp yerine ar[i] sayısını koyuyoruz. Nereye koyulacağını TreeSet'in add yöntemi ayarlıyor.
```
public int lengthOfLIS(int[] ar){
        TreeSet<Integer> set = new TreeSet<Integer>();
        for (int i=0; i<ar.length; i++) {
            Integer ceil = set.ceiling(ar[i]);
            if(ceil == null)     
                set.add(ar[i]);
            else{                   
                set.remove(ceil);
                set.add(ar[i]);
            }
        }
        return set.size();
    }
```
Not: öbür bölerek aaramalı çözümlerle (bunlar 2 ms) az çok aynı işlemi yapmasına rağmen submit edince 8 ms sürüyor. Bunun sebebi hep önceki öğeyi kaldırmak için hem de yenisini eklediğimiz için kullandığımız fazladan işlem olabilir. Array'lerde bu iki işlemi birlikte yapıyoruz, daha az bölerek arama yapıyoruz.

**Comment by altayhunoglu** [comment]
Tamamdır, 3 çözüm yöntemini de şurada eklemiş olduk:
https://github.com/altayhunoglu/algorithms/commit/c1d1281eca233260ba8f9eb510e7232ceb5e9555
