### ISSUE TITLE
364. Nested List Weight Sum II

### ISSUE THREAD

**Issue by altayhunoglu** [spiralgo/algorithms#11]
Burada "Nested List" iç içe geçmiş liste demektir.
Burada, listeler iç içe olduğunda bir ağırlık (weight) kavramı açığa çıkar.
Ama bu ağırlık kavramı, Nested List Weight Sum I sorusunun aksine, bu soruda tersten tanımlanmış.

Yani, parantezleri bir hapishane hücresi olarak düşünebiliriz. Ağırlığı ise, özgürlük oranı olarak. Dolayısı ile, ne kadar hücre içinde hücreye tıkılmışsak, o kadar özgürlükten uzağız demektir.

Yani, parantezlerin içindekiler daha az derinliğe sahipken, parantezin dışında çıkıldıkça ağırlık artıyor.
Örnek:
Input: [[1,1],2,[1,1]]
Output: 8 
Açıklama: 1'ler parantezin içinde olduklarından en az ağırlığa sahip yani 1 ağırlığına sahipler.
 2 ise, parantezin dışında olduğu için 2 ağırlığına sahip. 
 
 Input: [1,[4,[6]]]
Output: 17 
Explanation: 6 en çok parantezle çevrili olduğu için en az ağırlığa (1) sahip. Dışarı çıkıldıkça 4 biraz daha artan ağırlığa (2) sahip. 1 ise en dışta olduğu için en çok ağırlığa (3) sahip.
  1*3 + 4*2 + 6*1 = 17.

**Comment by ErdemT09** [comment]
Şu anki [çözüme](https://github.com/spiralgo/algorithms/blob/master/src/main/java/algorithms/curated170/medium/NestedListWeightSum2.java) ek olarak HashMap ve belki Queue ile de çözmek denenebilir.

**Comment by ErdemT09** [comment]
Solved:
https://github.com/spiralgo/algorithms/tree/master/src/main/java/algorithms/curated170/medium/nestedlistweightsum2
