### ISSUE TITLE
1120. Maximum Average Subtree

### ISSUE THREAD

**Issue by altayhunoglu** [spiralgo/algorithms#12]
https://leetcode.com/problems/maximum-average-subtree/

Bir ağaç veriliyor.
Bu ağacın alt dalları taranacak. Ortalaması en yüksek olan alt dal bulunup bu ortalama ekrana yazdırılacak.

Mesela ağaç:

```
      5
   /      \
6          1
```

Ağaç yukarıdaki gibi ise, root olan 5'de dahil olmak üzere ilk deneme yapılır:
 5+ 6 + 1= 12 bulunur. Ama 3 node toplama dahil edildiği için ortalama 4 bulunur.

 Sonra, soldaki alt-ağaç denenir ve toplam 5 olur. Toplama yalnızca 6 numaralı ağaç katıldığı için ortalama da 6'dır. 
 
Sağdaki alt-ağaç için ise ortalama 1'dir. 
Dolayısı ile ekrana 6 değeri yazılır. (Ortalama, bir bölme işlemi gerektiğinden sonuç double olarak bekleniyor. Ekrana 6.00000 yazdırılacaktır.)

**Comment by ErdemT09** [comment]
Solved:
https://github.com/spiralgo/algorithms/blob/master/src/main/java/algorithms/curated170/medium/MaximumAvarageSubtree.java
