### ISSUE TITLE
1165. Single-Row Keyboard

### ISSUE THREAD

**Issue by altayhunoglu** [spiralgo/algorithms#129]
Bütün harflerin tek bir satırda toplandığı özel bir klavye düşünüyoruz.
Bir "i" indeksinden, bir "j" indeksine gitmenin maliyeti |j-i| olarak verilmiş.
Çünkü klavye üzerinde, geriye doğru da gidilebiliyor. 

İlk örnekte olduğu gibi, bize bir klavye ve bir kelime veriliyor:
Input: keyboard = "abcdefghijklmnopqrstuvwxyz", word = "cba"

Buradan anladığımız şey, klavyedeki harflerin dizilimi, yani  calculateTime(String keyboard, String word)  methoduna gönderilen keyboard değerinin sürekli değişebileceği.

Bizden, bu klavyede "word" kelimesini yazma süremizi istiyor.

Yani:
Input: keyboard = "abcdefghijklmnopqrstuvwxyz", word = "cba"

Mesela bu örnekte, biz ilk olarak "0" indeksindeyiz yani "a" harfindeyiz.
O hâlde 2 birimlik yol kat ederek "c" harfine gidececeğiz.
Sonra 1 birimlik yol kat ederek "b" harfine gidececeğiz.
Sonra 1 birimlik yol kat ederek "a" harfine gidececeğiz.
Toplamda 4 birimlik yol kat ettik. Bu cevabı döndürmemiz isteniyor.

 

Constraints:

keyboard.length == 26
keyboard contains each English lowercase letter exactly once in some order.
1 <= word.length <= 104
word[i] is an English lowercase letter.

![image](https://user-images.githubusercontent.com/60903744/116747862-36740c00-aa07-11eb-9114-f4c9707860d9.png)

**Comment by ErdemT09** [comment]
> keyboard contains each English lowercase letter exactly once in some order. 
Yani klavyedeki harfler hep normal sprted alfabenin kaydırılmış hâli mi? Sorudaki örneklerde öyle de.

**Comment by altayhunoglu** [comment]
Evet. İngiliz alfabesindeki harflerin permutasyonları olarak düşünülebilir.

**Comment by ErdemT09** [comment]
Alfabenin permütasyonundan ziyada ["rotasyonu"](https://leetcode.com/problems/rotate-string/) olarak sormuştum. Eğer böyle bir şey geçerliyse belki HashMap kullanmadan alfabenin başlangıcının ve verilen stringin ASCII değeriyle ara işlemler yapılarak çözülebilir.

**Comment by altayhunoglu** [comment]
Güzel bir düşünce. Ancak soruda permutasyonun random değil de rotation ile oluşturulduğu garanti edilmemiş, anladığım kadarı ile.

Karakter sayısı 26 kesin olduğu için, indeksleri karakterlere göre haritalamak için HashMap yerine char array düşünülebilir.

**Comment by ErdemT09** [comment]
Solved:
https://github.com/spiralgo/algorithms/blob/master/src/main/java/algorithms/curated170/easy/SingleRowKeyboard.java

**Comment by altayhunoglu** [comment]
# The essence: 

> The time taken to move your finger from index i to index j is |i - j|.

**It is why the essence of the solution is storing the index of each character** (in order to be able to retrieve them in further steps.)

# Details:
You can use a map kind of data structure. Use the character as a key and the index as a value.
