### ISSUE TITLE
370. Range Addition

### ISSUE THREAD

**Issue by altayhunoglu** [spiralgo/algorithms#13]
https://leetcode.com/problems/range-addition/

Burada, bir arrayin uzunluğu veriliyor. (int length)
Bu uzunluk ile bir array yaratacağız ve bu arrayin ilk hâlinde, tüm elemanlar 0 değerine sahip.

Bir başka array de onlar tarafından veriliyor. (int[][] updates)
Bu array'de ise, bizim yarattığımız ilk array üzerinde yapılması gereken toplama işlemleri dair 3 adet bilgi liste halinde veriliyor.

startIndex: toplama işlemine hangi indeksten başlanacak.
endIndex: toplama işlemi hangi indekste bitirilecek.
inc: startIndex ile endIndex arasındaki elemanların her birine ne kadar eklenecek (eğer negatifse çıkarılacak)

Örnek:
Input: length = 5, updates = [[1,3,2],[2,4,3],[0,2,-2]]

Burada bizim yaratacağımız array 5 elemana sahip olmalı ve başlangıçta hepsi 0 olmalı.
updates içinde ise, mesela ilk elemanda:
startIndex= 1,
endIndex = 3,
inc= 2
olarak veriliyor. Yani, ilk işlemde, 1. indeksten, 3. indekse kadar olan her elemana 2 eklenecek.
Ardından diğer "update" işlemleride yapılınca şu sonuç elde ediliyor:

Output: [-2,0,3,5,3]

Bu sonucu da int[] türünde bir array ile göstereceğiz.

**Comment by ErdemT09** [comment]
Input basit bir biçimde (length=7, updates=[[1,3,a]]) olsun:
Bunun başlangıç yerine a koyup, bittiği yerin sonuna -a koyarsak ve array'in de öğelerini birikimli (kümülatif) toplarsak a kendi range'i, aralığı içerisinde a değerini sağlayacaktır. -a'da ise kendini sıfırlayp değerini sıfırlayacaktır ve array'in devamında gözükmeyecektir.
[0, a, 0, 0, -a, 0, 0] 
Bunu önceki öğeye eklemeli biçimde birikimli toplarsak:
[0, a, 0+a, 0+a, -a+a, 0, 0]  = [0, a, a, a, 0, 0, 0] gelir. Birden fazla, aralıkları üst üste gelen güncellemeler olduğunda da bu ilke geçerli kaldığı için bu algoritma verimli bir çözüm yöntemidir.

**Comment by altayhunoglu** [comment]
Teşekkürler Erdem, çok güzel açıklamışsın.

**Comment by ErdemT09** [comment]
Solved:
https://github.com/spiralgo/algorithms/blob/master/src/main/java/algorithms/curated170/medium/RangeAddition.java
