### ISSUE TITLE
760. Find Anagram Mappings

### ISSUE THREAD

**Issue by altayhunoglu** [spiralgo/algorithms#133]
İki dizi veriliyor: (int[] A, int[] B) 
Örnek:
> A = [12, 28, 46, 32, 50]
> B = [50, 12, 32, 46, 28]

A ve B'nin birbirinin anagramı olduğu söyleniyor. (*)
Yani A ve B integer dizileri aynı sayılardan oluşuyor.
A'daki tüm sayıların, B'deki indeksleri isteniyor.
Yukarıdaki örnekte,:
A dizisindeki 12 sayısının B dizisindeki indeksi "1" 
A dizisindeki 28 sayısının B dizisindeki indeksi "4" 
                       ...
A dizisindeki 50 sayısının B dizisindeki indeksi "0", olduğundan, cevap: **[1, 4, 3, 2, 0]**

Not: A ve B, aynı sayıyı birden fazla kez içerebilir.                   

(*: aslında bu noktada anagram kelimesi pek doğru değildir. Çünkü anagramın anlamlı bir kelime olması gerekir.
Örn: İngilizce "one" kelîmesi, "neo" kelîmesinin anagramıdır zirâ "e, n, o" harflerinin bu iki permutasyonu da anlamlıdır.)

![image](https://user-images.githubusercontent.com/60903744/116796561-094a5b00-aae6-11eb-8ded-ac1f4ed01e7f.png)

**Comment by ErdemT09** [comment]
Solved:
Java: https://github.com/spiralgo/algorithms/blob/master/src/main/java/algorithms/curated170/easy/FindAnagramMappings.java
Python: https://github.com/spiralgo/algorithms-python/blob/main/leetcode/curated170/easy/find_anagram_mappings.py

**Comment by altayhunoglu** [comment]
**The essence:**
Both arrays have the same elements but in a different order. 
We are asked for "indices" of the second array but by the order of the elements in the first array.
It means, we need to store the indices of the second array and traverse them by the order of the elements in the first array.

**Details:**

- You can use a map kind of data structure. Use the character as a key and the index as a value.
