### ISSUE TITLE
1134. Armstrong Number

### ISSUE THREAD

**Issue by altayhunoglu** [spiralgo/algorithms#136]
Verilen bir sayının Armstrong sayısı olup olmadığını döneceğiz.
Örnekte 153 sayısı verilmiş.
153 sayısı 3 basamaklıdır. 
Her bir basamağındaki sayının 3. dereceden kuvvetini alıp topladığımızda, gene 153'e eşit olduğu için, 153 bir Armstrong sayısıdır.

Varsayılan kod:
```
class Solution {
    public boolean isArmstrong(int n) {
        
    }
}
```

![image](https://user-images.githubusercontent.com/60903744/116796974-6dbae980-aae9-11eb-8afe-7bd05f3c4281.png)

**Comment by Umang228** [comment]
Can I work on this....

**Comment by altayhunoglu** [comment]
> Can I work on this....

Hello @Umang228,
Welcome.
Of course, you can work on any question you would like to contribute.
I'd be more than happy to help you whenever you want.

Best regards.

**Comment by Umang228** [comment]
Plz check PR https://github.com/spiralgo/algorithms/pull/164

**Comment by Umang228** [comment]
PR https://github.com/spiralgo/algorithms/pull/166

**Comment by altayhunoglu** [comment]
I approve of the solution, Umang.
Thank you for your valuable effort.
You are always welcome to have a look at other questions.
We can discuss any question that you have trouble with.

You can merge and delete the branch.

**Comment by altayhunoglu** [comment]
Solved using for-while loops:

https://github.com/spiralgo/algorithms/blob/master/src/main/java/algorithms/ArmstrongNumber.java
https://github.com/spiralgo/algorithms/blob/master/src/main/java/algorithms/curated170/easy/ArmstrongNumber.java
