### ISSUE TITLE
1196. How Many Apples Can You Put into the Basket

### ISSUE THREAD

**Issue by altayhunoglu** [spiralgo/algorithms#143]
_**int[] arr**_ adlı array içerisinde, elmaların ağırlıkları var.
Bir tâne de sepet var. Bu sepet en fazla 5000 birim taşıyabiliyor.
Sepete konulabilecek maksimum elma sayısı isteniyor.

Varsayılan kod:

```
class Solution {
    public int maxNumberOfApples(int[] arr) {
        
    }
}
```

![image](https://user-images.githubusercontent.com/60903744/116937605-2ad84d80-ac72-11eb-8d21-d03a624e476f.png)

**Comment by ErdemT09** [comment]
Solved:
https://github.com/spiralgo/algorithms/blob/master/src/main/java/algorithms/curated170/easy/HowManyApplesCanYouPutintotheBasket.java
