### ISSUE TITLE
243. Shortest Word Distance

### ISSUE THREAD

**Issue by altayhunoglu** [spiralgo/algorithms#147]
**wordsDict** sözlüğünün içindeki iki kelime veriliyor.
Bu iki kelimenin, sözlükte birbirine uzaklıklarının alabileceği en küçük değer soruluyor.
(Bu iki kelime de sözlükte birden fazla kez bulunabileceği için, birden fazla uzaklık söz konusu olabilir. Bunlardan minimum olanı isteniyor.

Varsayılan kod:

```
 class Solution {
    public int shortestDistance(String[] wordsDict, String word1, String word2) {
        
    }
} 

```
![image](https://user-images.githubusercontent.com/60903744/116938998-42b0d100-ac74-11eb-82e9-c6348ab09312.png)

**Comment by ErdemT09** [comment]
Solved:
https://github.com/spiralgo/algorithms/blob/master/src/main/java/algorithms/curated170/easy/ShortestWordDistance.java
