### ISSUE TITLE
426. Convert Binary Search Tree to Sorted Doubly Linked List

### ISSUE THREAD

**Issue by altayhunoglu** [spiralgo/algorithms#15]
https://leetcode.com/problems/convert-binary-search-tree-to-sorted-doubly-linked-list/

Burada "Binary Search Tree", binary tree'nin özel bir çeşidi idi. 
Bu özel çeşitte, bir ebeveynin sol tarafındaki tüm yavrular kendisine küçük veyâ eşit, sağındakiler ise kendisinden büyük olmaya mecbûrdur.

Aynı şekilde, Doubly Linked List de özel bir Linked List çeşididir.
Normal bir Linked List'te, bir node, yalnızca kendisinden sonraki (next, burada left ile belirtilmiş) node'a erişebilir. Doubly Linked List'te ise hem next hem de previous (burada right ile belirtilmiş) değerleri olduğu için, bir node kendisinden önceki node'a da erişebilir.

Bizden bir Binary Search Tree'yi, bir Doubly Linked Liste (sorted, yani sıralanmış halde) çevirmemiz isteniyor.

Hem ağaç hem de Doubly Linked List, aynı "Node" nesnelerinden oluşacak.
Bu dönüşümün "in-place" yani başka bir aracı veri yapısı kullanmadan, olduğu yerde yapılması isteniyor.
Bizden, Doubly Linked List'in en küçük (yani en baştaki) elemanını gösteren pointer'ı döndürmemiz isteniyor.

**Comment by altayhunoglu** [comment]
![image](https://user-images.githubusercontent.com/60903744/117353865-58fb9e80-aeb9-11eb-86bc-a579ecddcc00.png)
![image](https://user-images.githubusercontent.com/60903744/117353970-7a5c8a80-aeb9-11eb-9a52-c024dc3fcd06.png)

Solution for example-1:
![image](https://user-images.githubusercontent.com/60903744/117354039-8f391e00-aeb9-11eb-87a3-070717241092.png)
![image](https://user-images.githubusercontent.com/60903744/117354065-98c28600-aeb9-11eb-9c7f-946f3b9dc9ca.png)

**Comment by ErdemT09** [comment]
Solved:
https://github.com/spiralgo/algorithms/blob/master/src/main/java/algorithms/curated170/medium/ConvertBinarySearchTreeToDoublyLinkedList.java

**Comment by ErdemT09** [comment]
Çözümü şurada anlatmaya çalıştım:
https://youtu.be/OaC3ODVME7Y

**Comment by altayhunoglu** [comment]
Çok güzel oldu Erdem. Eline sağlık. Devamını dilerim.

**Comment by ErdemT09** [comment]
Bu çözümü gösterirken programdaki durumları teker teker gösterebilmek de önemliydi. Bunu bu tre için oklar ve koyu turkuaz renkli bir işaretçiyle göstermeye çalıştım. Farklı sorularda durumları göstermek için daha farklı stratejileri oluşturulabilir.
Bunu da algoritmaları öğretme algortimasının bir parçası olarak not edeyim.
