### ISSUE TITLE
1426. Counting Elements

### ISSUE THREAD

**Issue by altayhunoglu** [spiralgo/algorithms#150]
**int[] arr** tamsayı dizisi veriliyor. Dizideki elemanlardan, bir fazlası da aynı şekilde dizide yer alanlarının listesi isteniyor.

Varsayılan kod:

```
class Solution {
    public int countElements(int[] arr) {
        
    }
}
```

![image](https://user-images.githubusercontent.com/60903744/116941213-efd91880-ac77-11eb-9f6a-6daae29bbd15.png)
![image](https://user-images.githubusercontent.com/60903744/116941240-f9fb1700-ac77-11eb-8c58-46651bd8ef30.png)

**Comment by ErdemT09** [comment]
Solved:
https://github.com/spiralgo/algorithms/blob/master/src/main/java/algorithms/curated170/easy/CountingElements.java
https://github.com/spiralgo/algorithms/blob/master/src/main/java/algorithms/curated170/easy/CountingElementsLinear.java
https://github.com/spiralgo/algorithms/blob/master/src/main/java/algorithms/curated170/easy/CountingElementsSet.java
