### ISSUE TITLE
270. Closest Binary Search Tree Value

### ISSUE THREAD

**Issue by altayhunoglu** [spiralgo/algorithms#155]
Bir "Binary Arama Ağacı" veriliyor. Target değerine en yakın değere sahib node'un değeri isteniyor.

Varsayılan kod:

```
class Solution {
    public int closestValue(TreeNode root, double target) {
        
    }
}
```

![image](https://user-images.githubusercontent.com/60903744/116947965-bd82e780-ac86-11eb-923f-d0e0c6c714ef.png)
![image](https://user-images.githubusercontent.com/60903744/116947986-c96ea980-ac86-11eb-9782-ce649bf02029.png)

**Comment by ErdemT09** [comment]
This problem has another issue, where the solution is explained. https://github.com/spiralgo/algorithms/issues/95 
Solved:
https://github.com/spiralgo/algorithms/blob/master/src/main/java/algorithms/curated170/easy/ClosestBinarySearchTreeValue.java
