### ISSUE TITLE
1056. Confusing Number

### ISSUE THREAD

**Issue by altayhunoglu** [spiralgo/algorithms#156]
180 derece ters çevrildiklerinde elde edilen veri bakımından üç çeşit sayı var:
1- Confusing (kafa karıştırıcı) sayı:
180 derece çevrildiğinde başka bir sayı gibi görünen sayı.
Örnek: 69'u 180 derece çevirdiğinde 96 olur.

2- Geçersiz (invalid) sayı:  2, 3, 4, 5 rakamlarını içeren herhangi bir sayıdır.
180 derece çevrildiğinde, bir anlam ifade etmeyen sayı.
Örnek: 17

3- Ters çevrildiğinde kendisine eşit olan sayı:
Örnek: 11, 88

**Kısacası: bir sayı "2, 3, 4, 5" içermiyorsa ve ters çevrildiğinde kendisine eşit değilse  "confusing" sayıdır.**

Varsayılan kod:
```
class Solution {
    public boolean confusingNumber(int N) {
        
    }
}
```

![image](https://user-images.githubusercontent.com/60903744/116949190-3172bf00-ac8a-11eb-8d9e-0cbd0b749b6d.png)
![image](https://user-images.githubusercontent.com/60903744/116949210-3d5e8100-ac8a-11eb-8c16-66814e07dd03.png)
![image](https://user-images.githubusercontent.com/60903744/116949222-44858f00-ac8a-11eb-98b1-04db12812043.png)

(Java çözümü: https://github.com/spiralgo/algorithms/blob/master/src/main/java/algorithms/curated170/easy/ConfusingNumber.java)

**Comment by ErdemT09** [comment]
Solved:
https://github.com/spiralgo/algorithms/blob/master/src/main/java/algorithms/curated170/easy/ConfusingNumber.java
