### ISSUE TITLE
422. Valid Word Square

### ISSUE THREAD

**Issue by altayhunoglu** [spiralgo/algorithms#160]
Bir kelime listesi veriliyor. (List<String> word)
Bu kelime listesinin "geçerli bir kare" oluşturup oluşturmadığı soruyor.
Geçerli kare; aynı indeksli satır ve sütunlarında aynı metnin olması demektir.

Varsayılan kod:

```
class Solution {
    public boolean validWordSquare(List<String> words) {
        
    }
}
```

![image](https://user-images.githubusercontent.com/60903744/116950157-ddb5a500-ac8c-11eb-95ee-31444276dd18.png)
![image](https://user-images.githubusercontent.com/60903744/116950165-e4441c80-ac8c-11eb-8949-ad70c3ca7ee0.png)
![image](https://user-images.githubusercontent.com/60903744/116950174-ead29400-ac8c-11eb-896f-275307b27d4c.png)
![image](https://user-images.githubusercontent.com/60903744/116950194-f32acf00-ac8c-11eb-9ea4-270cd864d90d.png)

**Comment by ErdemT09** [comment]
Solved:
https://github.com/spiralgo/algorithms/blob/master/src/main/java/algorithms/curated170/easy/ValidWordSquare.java
