### ISSUE TITLE
170. Two Sum III - Data structure design

### ISSUE THREAD

**Issue by altayhunoglu** [spiralgo/algorithms#162]
TwoSum adında bir veri yapısı tasarlayacağız.
Bu veri yapısında bir dizi olacak ve bu diziye **add(int number)** methodu ile, mevcut diziye yeni sayılar eklenebilecek.
Toplamları **find(int value)** methoduyla verilen **value** parametresine eşit iki sayı olup olmadığını söyleyecek.

Varsayılan kod:
```
class TwoSum {

    /** Initialize your data structure here. */
    public TwoSum() {
        
    }
    
    /** Add the number to an internal data structure.. */
    public void add(int number) {
        
    }
    
    /** Find if there exists any pair of numbers which sum is equal to the value. */
    public boolean find(int value) {
        
    }
} 
```

![image](https://user-images.githubusercontent.com/60903744/116950796-d394a600-ac8e-11eb-83e9-70f0b9dd28db.png)
![image](https://user-images.githubusercontent.com/60903744/116950805-dabbb400-ac8e-11eb-9c56-45587955134b.png)

**Comment by Umang228** [comment]
Assign me....

**Comment by altayhunoglu** [comment]
> Assign me....
> 
> 

Hello Umang,

It js my fault that I did not inform you, some of the problems are already solved and merged.

It is one of them.

After we create a wiki page for these explanations, we will close the issues.

You can find the code under curated170/easy package.

But thought, thanks for your attention.

**Comment by altayhunoglu** [comment]
Solved:
https://github.com/spiralgo/algorithms/blob/master/src/main/java/algorithms/curated170/easy/TwoSumIII.java
