### ISSUE TITLE
163. Missing Ranges

### ISSUE THREAD

**Issue by altayhunoglu** [spiralgo/algorithms#163]
Bize lower ve upper sayıları veriliyor.
Lower'dan upper'a kadar artan sıralı bir dizi hayâl edelim.
Ama bu dizinin bazı aralıkları silinmiş.
İşte bu silinen aralıkları istiyor.

Varsayılan kod:
```
class Solution {
    public List<String> findMissingRanges(int[] nums, int lower, int upper) {
        
    }
}
```

![image](https://user-images.githubusercontent.com/60903744/116950869-09d22580-ac8f-11eb-90b4-6b0c954f8c8d.png)
![image](https://user-images.githubusercontent.com/60903744/116950875-10609d00-ac8f-11eb-84b7-84b6bb9dd3aa.png)
![image](https://user-images.githubusercontent.com/60903744/116950890-16567e00-ac8f-11eb-8b03-3b729290e618.png)
![image](https://user-images.githubusercontent.com/60903744/116950916-253d3080-ac8f-11eb-869b-3dd6cdec65f1.png)

**Comment by ErdemT09** [comment]
Solved:
https://github.com/spiralgo/algorithms/blob/master/src/main/java/algorithms/curated170/easy/MissingRanges.java
