### ISSUE TITLE
1538. Guess the Majority in a Hidden Array

### ISSUE THREAD

**Issue by altayhunoglu** [spiralgo/algorithms#17]
https://leetcode.com/problems/guess-the-majority-in-a-hidden-array/

**Bizden istenen, çoğunluktaki eleman hangisi olursa olsun (0 veya 1), o değeri içeren herhangi bir indexi döndürmek** 

Burada Hidden Array array dediği gizli bir array.
Yani biz onun elemanlarını göremiyoruz.
Bildiğimiz şey ise, tüm elemanları ya 0 veya 1 değerine sahip.

 Mesela 0'lar çoğunlukta ise, gizli arrayde 0 değerini içeren herhangi bir index'i göndermek.

Ama bu array hakkında bilgi alabilmemiz için bir interface (ArrayReader) veriliyoruz.
Bu interface'de iki adet method var:

int query(int a, int b, int c, int d):
  Sorgulama methodu.
  Bu methoda, küçükten büyüğe doğru sıralanmış 4 index gönderebiliyoruz.
 mesela: arrayde 0 , 1, 2, 3 indekslerinde bulunan değerlere dair bilgi almak istiyorsak 
 query(1, 2, 3, 4) şeklinde sorgulama yapıyoruz.
  Bu array bize sonucu aşağıdakiler gibi dönebilir:
   
   **4**: Eğer method 4 değerini döndürürse, elemanların dördü de aynı değere sahip (ya hepsi 0 ya hepsi 1).
   **2**: Eğer elemanlardan üçü 1, kalan bir tanesi ise 0 değerine sahipse (veya bunun tam tersi durum söz konusu ise)
   **0**: Eğer elemanların yarısı 0 yarısı 1 ise.
   
   Not: query() methodunu yalnızca 2*n kez çağırabileceğiz. Burada n, array'in uzunluğu. 
   
   
   Örnek 1:

Input: nums = [0,0,1,0,1,1,1,1]
Output: 5
Açıklama: reader.length() metodunu çağırarak array'in uzunluğunun 8 olduğunu öğreniriz.

reader.query(0,1,2,3):  bu sorgu bize 2 değerini gönderir. Çünkü sorgulanan dört indexin, üçü 0, kalan ise 1 değerine sahip.
 
reader.query(4,5,6,7) : bu sorgu bize 4 değerini gönderir. Çünkü sorgulanan 4 eleman da 1 değerine sahip.
Bu sorgu ile, en çok elemanın sondaki dört elemanda olduğunu anlarız. 
Bizim bu elemanın 0 mı, yoksa 1'mi olduğunu bilmeye ihtiyacımız yok.
Dolayısı ile biz 4, 5, 6, 7 değerlerinden herhangi birini sonuç olarak gönderebiliriz.

**Comment by ErdemT09** [comment]
Solved:
https://github.com/spiralgo/algorithms/blob/master/src/main/java/algorithms/curated170/medium/GuessTheMajorityInAHiddenArray.java
