### ISSUE TITLE
1522. Diameter of N-Ary Tree

### ISSUE THREAD

**Issue by altayhunoglu** [spiralgo/algorithms#174]
Diameter'in ne olduğu şu benzer soruda soruda açıklanmıştı:
https://github.com/spiralgo/algorithms/issues/16

Varsayılan kod:
```
class Solution {
    public int diameter(Node root) {
        
    }
}
```
![image](https://user-images.githubusercontent.com/60903744/117478340-b0f0de80-af67-11eb-9b6d-c545661a0eaa.png)
![image](https://user-images.githubusercontent.com/60903744/117478360-b8b08300-af67-11eb-8712-6bcb4a0be7df.png)
![image](https://user-images.githubusercontent.com/60903744/117478396-c239eb00-af67-11eb-86c2-2984070769bb.png)
![image](https://user-images.githubusercontent.com/60903744/117478408-c7973580-af67-11eb-8bcc-3c19e74869d3.png)

Çözüldüğü için direkt kapatıyorum.
https://github.com/spiralgo/algorithms/blob/master/src/main/java/algorithms/curated170/medium/DiameterofNAryTree.java

**Comment by ErdemT09** [comment]
Now thinking, I want to note that this is nearly the same question as this:
https://github.com/spiralgo/algorithms/pull/173

**Comment by altayhunoglu** [comment]
You are right.
