### ISSUE TITLE
1101. The Earliest Moment When Everyone Become Friends

### ISSUE THREAD

**Issue by altayhunoglu** [spiralgo/algorithms#185]
Varsayılan kod:
```
class Solution {
    public int earliestAcq(int[][] logs, int N) {
        
    }
}
```

![image](https://user-images.githubusercontent.com/60903744/117588016-83539300-b129-11eb-8aef-79b90fb4b03c.png)
![image](https://user-images.githubusercontent.com/60903744/117588021-8babce00-b129-11eb-9e24-01fbf29ffb12.png)
![image](https://user-images.githubusercontent.com/60903744/117588026-94040900-b129-11eb-9e06-68b3e19bac41.png)

**Comment by altayhunoglu** [comment]
Solved: https://github.com/spiralgo/algorithms/issues/31

**Comment by ErdemT09** [comment]
Solved:
https://github.com/spiralgo/algorithms/blob/master/src/main/java/algorithms/curated170/medium/TheEarliestMomentWhenEveryoneBecomeFriends.java
