### ISSUE TITLE
510. Inorder Successor in BST II

### ISSUE THREAD

**Issue by altayhunoglu** [spiralgo/algorithms#19]
https://leetcode.com/problems/inorder-successor-in-bst-ii/
 
 Burada bir Binary Search Tree sorusu söz konusu.
 Yani, ağacın solundaki tüm değerler, root'tan küçük, sağındakiler ise büyük.
 
Bize bu ağaçtaki herhangi bir "node" veriliyor. Node içerisinde onun "parent" değerine erişmemizi sağlayan bir de parent node nesnesi var. 
 Yani bize, ağacın root'u değil, herhangi bir node veriliyor. 
class Node {
    public int val;
    public Node left;
    public Node right;
    public Node **parent**;
}

İşte, bize verilen bu node'dan bir sonraki değer soruluyor. Bir sonraki değeri, ağacı "in-order" sıralayarak bulacağız.

**Comment by ErdemT09** [comment]
Solved:
https://github.com/spiralgo/algorithms/blob/master/src/main/java/algorithms/curated170/medium/InorderSuccessorInBST2.java
