### ISSUE TITLE
1244. Design A Leaderboard

### ISSUE THREAD

**Issue by altayhunoglu** [spiralgo/algorithms#2]
https://leetcode.com/problems/design-a-leaderboard/

Bu soruda, bir skor tahtası dizayn etmemiz isteniyor.
 addScore(playerId, score) methodu ile, bir oyuncunun skoru “artırılacak”
Eğer o oyuncuya dair hiç skor yoksa, direkt score değerinin kendisi konulacak.
Demek ki, bir HashMap<Integer, Integer> depo olarak iş görür.

top(K): methodunda, en yüksek skora sahip K sayıdaki sporcunun toplam skoru isteniyor.
Burada, depodaki listeyi, skora göre sıralamak gerekebilir.
reset(playerId): burada, id’si verilen sporcunun skorunun sıfırlanması isteniyor. Depodaki skor sıfırlanabilir.

**Comment by ErdemT09** [comment]
Solved:
https://github.com/spiralgo/algorithms/tree/master/src/main/java/algorithms/curated170/medium/designaleaderboard
