### ISSUE TITLE
635. Design Log Storage System

### ISSUE THREAD

**Issue by altayhunoglu** [spiralgo/algorithms#20]
https://leetcode.com/problems/design-log-storage-system/

 Burada bir loglama sistemi dizayn edeceğiz.
 Her bir log, şu şekilde iki değer içerecek:
[1, "2017:01:01:23:59:59"], burada 1, logun ID değeri.  "2017:01:01:23:59:59" ise logun geldiği tarihi belirten bir timestamp ve string türünde.

Loglama sistemini LogSystem diye bir sınıf içinde kodlayacağız. Bu sınıf bazı metodlara sahip olacak:

LogSystem(): bu constructor method. Yani sınıf ile ilgili ilk bilgiler burada oluşturulacak.

void put(int id, string timestamp): bu, log deposuna yeni log eklemekte kullanılacak. 

int[] retrieve(string start, string end, string granularity): Bu, start ve end tarihleri arasındaki tüm logları getirecek. granularity dediği şey ise, verilen tarih aramasını nasıl bir kesinlikte yapacağımız yönünde. Mesela granularity: Day, month, year olabilir.

Örnek:

Örneğin, start = "2017:01:01:23:59:59", end = "2017:01:02:23:59:59", ve granularity = "Day" şeklinde verilse idi, 1 Ocak 2017 to ve 2 Ocak 2017 arasındaki tüm logları getirecektik. Granularity "day" olduğu için, gün değerinden küçük olan saat, dakika, saniye gibi zamanları önemsemeyeceğiz.

**Comment by ErdemT09** [comment]
Solved:
https://github.com/spiralgo/algorithms/blob/master/src/main/java/algorithms/curated170/medium/DesignLogStorageSystem.java
