### ISSUE TITLE
531. Lonely Pixel I

### ISSUE THREAD

**Issue by altayhunoglu** [spiralgo/algorithms#21]
https://leetcode.com/problems/lonely-pixel-i/

 Burada bir çok boyutlu array (char[][] picture) veriliyor.
 Bu arrayin bâzı elemanları "B" (black, siyah), bazı elemanları ise "W" karakterini içeriyor.

 Bizden istenen ise, "B" karakterinin yalnız olduğu durumların sayısı.
 "B"nin yalnız olması, onun bulunduğu satırda ve sütunda başka hîçbir "B" harfinin olmadığı durum demektir.

**Comment by ErdemT09** [comment]
Elimizde şöyle bir grid var diyelim:
W W B W W
W B W W B
B W W B W
W B W W B
B W W W W
W W W W B

Bu grid'i teker teker loop'luyoruz.
picture[0][2]'deki B'ye denk geldik. B'nin sütun ve satırını kontrol ederiz. Eğer bir B ile karşılaşmazsak lonely pixel'dır. Sayacımızı increment ederiz. Eğer bir B ile karşılaşırsak bu B'yi 'C ' gibi başka bir char değeri yaparız, böylece bunu tekrar kontrol etmek zorunda kalmayız. İlk B  bir şey bulmaz => sayacı 1 arttır.
picture[1][1]'deki B'ye denk geldik. Bu kez B ile karşılaşırız, yukarıdaki işlemi yaparız.
W W B W W
W B W W C
B W W B W
W C W W B
B W W W W
W W W W B
Grid'i loop'larken karşılaştığımız 'C'lere bakmayız; çünkü onların lonely olmadıklarını biliyoruz.
Bu işlemi tüm grid için tekrar edersek şöyle bir yapı ortaya çıkar:
W W B W W
W B W W C
B W W C W
W C W W B
C W W W W
W W W W C

Bu 4 lonely pixel var demek değil, 4*2 (her birinde sütunve satıra bakma) tane işlem yaptık demek. Sayacımız yalnızca baştaki 'B'de satır-sütunda bir şey bulamadı.
Bunu şöyle koda dökebiliriz:
```
public static int findLonelyPixel(char[][] pixels) {
        int count = 0;
        for (int i = 0; i < pixels.length; i++) {
            for (int j = 0; j < pixels[i].length; j++) {
                boolean lonely = true;
                if (pixels[i][j] == 'B') {
                    for (int k = 0; k < pixels.length; k++) {
                        if (k != i && (pixels[k][j] == 'B' || pixels[k][j] == 'C')) {
                            lonely = false;
                            pixels[k][j] = 'C';
                        }
                    }
                    for (int k = 0; k < pixels[i].length; k++) {
                        if (k != j && (pixels[i][k] == 'B' || pixels[i][k] == 'C')) {
                            lonely = false;
                            pixels[i][k] = 'C';
                        }
                    }
                    if (lonely) {
                        count++;
                    }
                }
            }
        }
        return count;
    }
```
Ek olarak, eğer bir satırda 'C' ile karşılaşırsak, o satırı tamamen es de geçebiliriz. Bunu da şöyle ekleyebiliriz:
```
public static int findLonelyPixel1(char[][] pixels) {
        int count = 0;
        for (int i = 0; i < pixels.length; i++) {
            for (int j = 0; j < pixels[i].length; j++) {
                boolean lonely = true;
                if(pixels[i][j] == 'C')
                {
                    break;
                }
                if (pixels[i][j] == 'B') {
                    for (int k = 0; k < pixels.length; k++) {
                        if (k != i && (pixels[k][j] == 'B' || pixels[k][j] == 'C')) {
                            lonely = false;
                            pixels[k][j] = 'C';
                        }
                    }
                    for (int k = 0; k < pixels[i].length; k++) {
                        if (k != j && (pixels[i][k] == 'B' || pixels[i][k] == 'C')) {
                            lonely = false;
                            pixels[i][k] = 'C';
                        }
                    }
                    if (lonely) {
                        count++;
                    }
                }
            }
        }
        return count;
    }
```
Ortalam durumlarda grid'i 2 kezden az tarıyoruz. En kötü durumda ('B'lerin hepsi çapraz sıralandığında) 2 kez tarıyoruz.

**Comment by ErdemT09** [comment]
Sütunları da es geçmek için, satır tararken bulduğumuz bir 'B'nin sütun başını da 'C' yapabiliriz:
```
ublic static int findLonelyPixel2(char[][] pixels) {
        int count = 0;
        for (int i = 0; i < pixels.length; i++) {
            for (int j = 0; j < pixels[i].length; j++) {
                boolean lonely = true;
                if(pixels[i][j] == 'C')
                {
                    break;
                }
                if (pixels[i][j] == 'B') {
                    for (int k = 0; k < pixels.length; k++) {
                        if (k != i && (pixels[k][j] == 'B' || pixels[k][j] == 'C')) {
                            lonely = false;
                            pixels[k][j] = 'C';
                        }
                    }
                    for (int k = 0; k < pixels[i].length; k++) {
                        if (k != j && (pixels[i][k] == 'B' || pixels[i][k] == 'C')) {
                            lonely = false;
                            pixels[i][k] = 'C';
                            pixels[0][k] = 'C';
                        }
                    }
                    if (lonely) {
                        count++;
                    }
                    else
                    {
                        break;
                    }
                }
            }
        }
        return count;
    }
```

**Comment by altayhunoglu** [comment]
Selâmlar Erdem,

Anlaştığımız gibi, aşağıdaki çözümü ekledim.

https://github.com/spiralgo/algorithms/commit/cc3b30600c16b2df09a7e64a1463a1f223bb8dbf

**Comment by ErdemT09** [comment]
Solved:
https://github.com/spiralgo/algorithms/blob/master/src/main/java/algorithms/curated170/medium/LonelyPixel1.java
