### ISSUE TITLE
1259. Handshakes That Don't Cross

### ISSUE THREAD

**Issue by altayhunoglu** [spiralgo/algorithms#216]
Varsayılan kod:

```
class Solution {
    public int numberOfWays(int num_people) {
        
    }
}
```

![image](https://user-images.githubusercontent.com/60903744/118380356-d0cc7600-b5e9-11eb-8953-1aa873a6db56.png)
![image](https://user-images.githubusercontent.com/60903744/118380362-d75aed80-b5e9-11eb-8236-124cc777ad9a.png)
![5125_example_3](https://user-images.githubusercontent.com/60903744/118380375-ea6dbd80-b5e9-11eb-84de-e2b33b1f7b1c.png)
![image](https://user-images.githubusercontent.com/60903744/118380377-f48fbc00-b5e9-11eb-9fde-2bf25eee885c.png)

**Comment by altayhunoglu** [comment]
https://www.youtube.com/watch?v=0pTN0qzpt-Y&ab_channel=KeertiPurswaniKeertiPurswani

**Comment by ErdemT09** [comment]
In each handshake, we divide the "hands" into two different groups, and calculate how many such division we can make in turn in those divisions. Like in #338, this is related to Catalan numbers somehow, I think.

**Comment by ErdemT09** [comment]
The recursive formula should look something like this:
handshakes(n) := hs(n)
hs(n) := hs(0)*hs(n-2) + hs(2)*hs(n-4) + hs(4)*hs(n-6) ... + hs(n-2)*hs(0)
