### ISSUE TITLE
369. Plus One Linked List

### ISSUE THREAD

**Issue by altayhunoglu** [spiralgo/algorithms#22]
https://leetcode.com/problems/plus-one-linked-list
Bir Linked List veriliyor. 
Bu Linked List'in her bir nodunda, bir sayının bir basamağı var.
Mesela 123 sayısının,:1 rakamı ilk node, 2 rakamı ikinci node, 3 rakamı ise en son node içerisinde.

İşte Linked List içerisinde depolanan bu sayıyı 1 artırıp ekrana yazacağız.

**Comment by ErdemT09** [comment]
Medium denilebilmek için gerçekten kolay bir soru. LeetCode'un sınıflandırmalarının dengesizliğini gösteriyor.

**Comment by ErdemT09** [comment]
Solved:
https://github.com/spiralgo/algorithms/blob/master/src/main/java/algorithms/curated170/medium/PlusOneLinkedList.java
