### ISSUE TITLE
774. Minimize Max Distance to Gas Station

### ISSUE THREAD

**Issue by altayhunoglu** [spiralgo/algorithms#223]
Varsayılan kod:
```
class Solution {
    public double minmaxGasDist(int[] stations, int k) {
        
    }
}
```
![image](https://user-images.githubusercontent.com/60903744/118380586-92d05180-b5eb-11eb-9ada-9c0b8c2cc9d1.png)
![image](https://user-images.githubusercontent.com/60903744/118380589-9b288c80-b5eb-11eb-917c-c478da1fa999.png)

**Comment by ErdemT09** [comment]
https://codingcompetitions.withgoogle.com/kickstart/round/000000000019ffc7/00000000001d3f5b
Same question.
