### ISSUE TITLE
358. Rearrange String k Distance Apart

### ISSUE THREAD

**Issue by altayhunoglu** [spiralgo/algorithms#238]
Varsayılan kod:

```
class Solution {
    public String rearrangeString(String s, int k) {
        
    }
}
```

![image](https://user-images.githubusercontent.com/60903744/118380907-57835200-b5ee-11eb-90fc-2a0de3b408b5.png)
![image](https://user-images.githubusercontent.com/60903744/118380918-6b2eb880-b5ee-11eb-848e-f87a87395b45.png)

**Comment by ErdemT09** [comment]
char'ların kaç kez geldiğini sayıp ondan sonra hepsini bir bir koymak çözüm sanırım, eğer aynı char'ı verilen uzaklıktan önce koyuyorsak çalışmıyordur ve boş string döndürürüz.

**Comment by ErdemT09** [comment]
Solved:
https://github.com/spiralgo/algorithms/blob/master/src/main/java/algorithms/curated170/hard/RearrangeStringKDistanceApart.java
https://github.com/spiralgo/algorithms/blob/master/src/main/java/algorithms/curated170/hard/RearrangeStringKDistanceApartArray.java
https://github.com/spiralgo/algorithms/blob/master/src/main/java/algorithms/curated170/hard/RearrangeStringKDistanceApartArrayLayers.java
