### ISSUE TITLE
1135. Connecting Cities With Minimum Cost

### ISSUE THREAD

**Issue by altayhunoglu** [spiralgo/algorithms#24]
https://leetcode.com/problems/connecting-cities-with-minimum-cost/

Burada, şehirler sayılarla temsil ediliyor.
A şehri ile B şehrini harita üzerinde bir çizgi ile birleştirdiğimizi düşünün.
Bu birleştirme işleminin bir maliyeti olsun. 
İşte bir çok boyutlu arrayde (int[][] connections, bu iki şehir ve bu maliyet tutuluyor. 

Bizden istenen, bu maliyeti minimumda tutarak tüm şehirleri birleştirmenin bir yolu olup olmadığını bulmak.
Bir yolu varsa maliyeti, yoksa -1 döndüreceğiz.

Örnek: 
Input: N = 3 (şehir sayısı) , connections = [[1,2,5],[1,3,6],[2,3,1]]
Burada:
[1,2,5] :  1 numaralı şehir ile 2 numaralı şehri bir çizgi ile birleştirme maliyetinin 5 olduğunu
[1,3,6]:   1 numaralı şehir ile 3 numaralı şehri bir çizgi ile birleştirme maliyetinin 6 olduğunu
[2,3,1]:   2 numaralı şehir ile 3 numaralı şehri bir çizgi ile birleştirme maliyetinin 1 olduğunu

Dolayısı ile, bu üç şehri birleştirmek için: [1,2,5] ve [2,3,1]

Örnek-2:
Bazen tüm şehirleri birleştirmenin bir yolu yoktur.
Mesela:  
 N = 4, (dört adet şehir olduğunu) gösterir.
connections = [[1,2,3],[3,4,4]]  içindeki ilk dizi [1, 2, 3]:   1 numaralı şehir ile 2 numaralı şehri bir çizgi ile birleştirme maliyetinin 3 olduğunu; 3 numaralı şehir ile 4 numaralı şehri bir çizgi ile birleştirme maliyetinin 4 olduğunu söylüyor.
Ama bağlantılar (connections) incelendiğinde, bu 4 şehri birleştirmenin bir yolu verilmemiş. Bu yüzden -1 döndüreceğiz.

**Comment by altayhunoglu** [comment]
public class Solution {
   public int minimumCost(int N, int[][] connections) {
        DisjointSet disjointset = new DisjointSet(N);
        // Sort connections based on their weights (in increasing order)
        Arrays.sort(connections, (a, b) -> a[2] - b[2]);
        // Keep track of total edges added in the MST
        int total = 0;
        // Keep track of the total cost of adding all those edges
        int cost = 0;
        for (int i = 0; i < connections.length; ++i) {
            int a = connections[i][0];
            int b = connections[i][1];
            // Do not add the edge from a to b if it is already connected
            if (disjointset.isInSameGroup(a, b)) continue;
            // If a and b are not connected, take union
            disjointset.union(a, b);
            // increment cost
            cost += connections[i][2];
            // increment number of edges added in the MST
            total++;
        }
        // If all N nodes are connected, the MST will have a total of N - 1 edges
        if (total == N - 1) {
            return cost;
        } else {
            return -1;
        }
    }
}
 

class DisjointSet {
    private int[] rank; // Used to store weights of each nodes 
    private int[] parent;

 // Perform Union of two subsets
    public void union(int a, int b)
    {
        // find the root of the sets in which elements
        // `x` and `y` belongs
        int x = find(a);
        int y = find(b);
 
        // if `x` and `y` are present in the same set
        if (x == y) {
            return;
        }
 
        // Always attach a smaller depth tree under the
        // root of the deeper tree.
        if (rank[x] > rank[y]) {
            parent[y] = x;
        }
        else if (rank[x] < rank[y]) {
            parent[x] = y;
        }
        else {
            parent[x] = y;
            rank[y] = rank[y] + 1;
        }
    }
    // Find the root of the set in which element `k` belongs
    public int find(int k)
    {
        // if `k` is not the root
        if (parent[k] != k)
        {
            // path compression
            parent[k] = find(parent[k]);
        }
 
        return parent[k];
    }
 

    public boolean isInSameGroup(int a, int b) {
        // Return true if both a and b belong to the same set, otherwise return false
        return find(a) == find(b);
    }

    // Initialize weight for each node to be 1
    public DisjointSet(int N) {
        parent = new int[N + 1];
        this.rank = new int[N + 1];
        // Set the initial parent node to itself
        for (int i = 1; i <= N; ++i) {
            parent[i] = i;
            this.rank[i] = 0;
        }
    }
}

**Comment by ErdemT09** [comment]
Solved:
https://github.com/spiralgo/algorithms/blob/master/src/main/java/algorithms/curated170/medium/ConnectingCitiesWithMinimumCost.java
