### ISSUE TITLE
1485. Clone Binary Tree With Random Pointer

### ISSUE THREAD

**Issue by altayhunoglu** [spiralgo/algorithms#259]
Varsayılan kod:
```
/**
 * Definition for Node.
 * public class Node {
 *     int val;
 *     Node left;
 *     Node right;
 *     Node random;
 *     Node() {}
 *     Node(int val) { this.val = val; }
 *     Node(int val, Node left, Node right, Node random) {
 *         this.val = val;
 *         this.left = left;
 *         this.right = right;
 *         this.random = random;
 *     }
 * }
 */

class Solution {
    public NodeCopy copyRandomBinaryTree(Node root) {
        
    }
}
```

![image](https://user-images.githubusercontent.com/60903744/118417933-07c08b80-b6bf-11eb-9888-11d84b491255.png)
![image](https://user-images.githubusercontent.com/60903744/118417942-1149f380-b6bf-11eb-9094-88350980f285.png)
![image](https://user-images.githubusercontent.com/60903744/118417947-16a73e00-b6bf-11eb-8731-4f714eedf59b.png)

**Example 2:**
![clone_2](https://user-images.githubusercontent.com/60903744/118417954-1f980f80-b6bf-11eb-87c1-ba4756797649.png)
![image](https://user-images.githubusercontent.com/60903744/118417971-2de62b80-b6bf-11eb-9d94-7ff17061b013.png)

**Example 3:**
![clone_3](https://user-images.githubusercontent.com/60903744/118417986-39d1ed80-b6bf-11eb-8989-4b330170b03f.png)
![image](https://user-images.githubusercontent.com/60903744/118418004-4ce4bd80-b6bf-11eb-9f1d-200e1323727d.png)
![image](https://user-images.githubusercontent.com/60903744/118418009-52da9e80-b6bf-11eb-8970-0211c84157b0.png)

**Comment by ErdemT09** [comment]
Solved:
https://github.com/spiralgo/algorithms/blob/master/src/main/java/algorithms/curated170/medium/CloneBinaryTreeWithRandomPointer.java
