### ISSUE TITLE
1166. Design File System

### ISSUE THREAD

**Issue by altayhunoglu** [spiralgo/algorithms#26]
https://leetcode.com/problems/design-file-system/

 Bilgisayarlardaki dosya sistemini taklit eden bir sınıf yazmamız isteniyor.

 Bu sınıfta iki tane method var:
   
    **public boolean createPath(String path, int value):** 
   Bunun aracılığı ile bir path, yani dosya yolu yaratacağız ve dosyanın içine value değişkenindeki değer atanacak.
   Eğer dosya sağlıklı bir şekilde yaratılırsa "true" boolean değerini döneceğiz.
   Eğer dosya hâlihazırda varsa veya "parent" dosyası henüz yaratılmamışsa, "false" boolean değerini döndüreceğiz.
    
    **public int get(String path)**: Verilen dosya yolundaki değer okunacak.

 Not: path'in alabileceği değerlere örnekler:
 **"/leetcode/problems"**
 
Bu yüzden "" veya "/" geçerli path değerleri değildir.

Örnek:
FileSystem fileSystem = new FileSystem();

fileSystem.createPath("/a", 1); // return true
fileSystem.get("/a"); // return 1

Seçtiğimiz çözüm kodu için ipucu:

> Burada delimit = delimiter = sınırlayıcı demek.

> [01:35, 3/26/2021] Altay: int delimIndex = path.lastIndexOf("/");
> [01:35, 3/26/2021] Altay: diyelim ki **path = "a/b/c"**
> [01:35, 3/26/2021] Altay: o hâlde, 
> int delimIndex = path.lastIndexOf("/");
> [01:36, 3/26/2021] Altay: bu kod bize, "/" sembolünün en son görüldüğü indexi verir.
> [01:36, 3/26/2021] Altay: Bunu yapma amacı nedir?
> [01:36, 3/26/2021] Altay: Meselâ Windows'ta bir dosya yaratmak istiyorsun diyelim
> [01:36, 3/26/2021] Altay: mesela C klasöründe "C:/a/b/c"
> [01:37, 3/26/2021] Altay: bu yolda "c" diye bir dosya yaratabilmen için
> [01:37, 3/26/2021] Altay: önce "c:/a/b" yolunun orada bulunması gerek.
> [01:37, 3/26/2021] Altay: dediğin gibi, parent c:/a/b/ olduğu için.
> [01:37, 3/26/2021] Altay: bu da HashMap'te parent var mı diye soruyor o yüzden

"value" değişkeni ile create methoduna ne gönderildi ise, onu da hashmapin value'si olarak kullanıyor

Varsayılan kod:
```
class FileSystem {

    public FileSystem() {
        
    }
    
    public boolean createPath(String path, int value) {
        
    }
    
    public int get(String path) {
        
    }
}
```
![image](https://user-images.githubusercontent.com/60903744/117577274-d14ca480-b0f1-11eb-9c6c-1e21145bdd13.png)
![image](https://user-images.githubusercontent.com/60903744/117577427-664f9d80-b0f2-11eb-9908-d2b70a40b310.png)
![image](https://user-images.githubusercontent.com/60903744/117577320-fe995280-b0f1-11eb-9b57-5a33d9962424.png)
![image](https://user-images.githubusercontent.com/60903744/117577327-03f69d00-b0f2-11eb-929c-b1a81669c456.png)

**Comment by ErdemT09** [comment]
"/d/e/" geçerli bir input olamaz, değil mi?

**Comment by altayhunoglu** [comment]
> "/d/e/" geçerli bir girdi olamaz, değil mi?

Resimler eklendi ve bazı düzenlemeler konuldu.

 Zannedersem "/d/e/" iki nedenle olmaz:
 - Dosya (aslında dizin) yaratırken, sadece başa "/" koymamız gerekiyor anladığım kadarı ile.
 - Henüz "/d" yaratırlmadığı için, "d" klasörünün altında "e" de yaratamayız.
 
 Ama şu şekilde doğru olurdu:
 
```
 FileSystem fileSystem = new FileSystem();

fileSystem.createPath("/d", 1); // return true
fileSystem.get("/d"); // return 1

fileSystem.createPath("/d/e", 9); // return true
fileSystem.get("/d/e"); // return 9  
```

**Comment by ErdemT09** [comment]
Solved:
https://github.com/spiralgo/algorithms/blob/master/src/main/java/algorithms/curated170/medium/DesignFileSystem.java
