### ISSUE TITLE
249. Group Shifted Strings

### ISSUE THREAD

**Issue by altayhunoglu** [spiralgo/algorithms#28]
https://leetcode.com/problems/group-shifted-strings

 İngiliz alfabesini düşünelim.
 
Bu alfabede "üç birimlik bir pencere" ile gezdiğimizi düşünelim.
Gezme işini, bir sonraki harfe kaymak (shifting) şeklinde yapacağız.
Dolayısı ile şöyle bir dizi açığa çıkardı:

"abc" -> "bcd" -> ... -> "xyz"

Eğer ikişer ikişer gezse idi, şuna benzerdi:
"ab" -> "cd" -> ... -> "yz"

Gezmek için pencere boyutunu yeniden şekillenebilir veya pencere istenildiği noktadan başlatılabilir. 
Alfabe sonuna gelindi ise, tekrar başa döndüğü düşünülecek.

İşte, bize (String[] strings) içinde -> "xyz",  -> "yz" sonuçlarında olduğu gibi bazı String parçaları veriyor.
 Bunların, aynı gezintiye ait olanlarını listeleyeceğiz.
 Yani  "yz" ile "cd" aynı türde gezintinin bir çıktısıdır. 
 Ama "xyz" ile "a" aynı gezintinin çıktıları olamaz. Pencere uzunluğu farklı.

Örnek:
Input: ["abc", "bcd", "acef", "xyz", "az", "ba", "a", "z"],
Output: 
[
  ["abc","bcd","xyz"],
  ["az","ba"],
  ["acef"],
  ["a","z"]
]

Varsayılan kod:
```
class Solution {
    public List<List<String>> groupStrings(String[] strings) {
        
    }
}
```

![image](https://user-images.githubusercontent.com/60903744/117666753-df133000-b1ac-11eb-91ee-c70bd7811f85.png)
![image](https://user-images.githubusercontent.com/60903744/117666777-e5091100-b1ac-11eb-8c1f-047dc9ec1b13.png)

**Comment by ErdemT09** [comment]
Solved:
https://github.com/spiralgo/algorithms/blob/master/src/main/java/algorithms/curated170/medium/GroupShiftedStrings.java
