### ISSUE TITLE
1564. Put Boxes Into the Warehouse I

### ISSUE THREAD

**Issue by altayhunoglu** [spiralgo/algorithms#3]
https://leetcode.com/problems/put-boxes-into-the-warehouse-i/
 
 Pozitif integer içeren iki array veriliyor:
  int[] boxes: kutuların uzunlukları. 
  int[] warehouse: kutuların konulacağı ambarların uzunlukları.
                            n adet ambar bulunuyor. Mesela warehouse[0], ilk ambarın uzunluğunu saklıyor.

**warehouse'a konulacak maximum kutu sayısı isteniyor.**

Not: 
Soruyu anlamak için LeetCode sitesindeki resimlere bakmak çok daha yararlı olacaktır.

Kutular ambarlara şu kurallarla konulacak:
 - Kutular üst üste konulamaz (cannot be stacked)
 - Kutuları koyma sıranızı değiştirebilirsiniz
 - Kutular, ambara sâdece soldan sağa doğru konulabilir.
 - Eğer kutulardan herhangi birisi, bir odanın yüksekliğinden daha yüksek ise işlem sonlandırılacak ve maksimum kutu sayısı gösterilecek.

**Comment by ErdemT09** [comment]
Solved:
https://github.com/spiralgo/algorithms/blob/master/src/main/java/algorithms/curated170/medium/PutBoxesIntoTheWarehouse1.java
