### ISSUE TITLE
323. Number of Connected Components in an Undirected Graph

### ISSUE THREAD

**Issue by altayhunoglu** [spiralgo/algorithms#31]
https://leetcode.com/problems/number-of-connected-components-in-an-undirected-graph

Undirected Graph, node'ların belli bir yönü olmaması demektir.
Bu yüzden [0 ,1] bağlantısı ile [1, 0] bağlantısı aynı şeydir ve 0 numaralı node'dan, 1 numaralı node'a bir bağlantı olduğunu gösterir.
Bu bağlantı çizgisine kenar (edge) denir.

Bize bu kenarların bir array'i (int[][] edges) ve node sayısı (n) veriliyor.

Bu bağlantıları kullanarak oluşan bileşen sayısını bulun diyor. 

Meselâ her bir node'u bir lego parçası olarak düşünelim. 
Bu array (int n, int[][] edges), hangi legonun hangisi ile bağlandığını gösteriyor. Sonuçta ortaya birden fazla "büyük lego" (bileşen, component) çıkabileceği gibi, tek bir büyük lego da çıkabilir.

İşte bu ortaya çıkan lego sayısı soruluyor.

**Comment by ErdemT09** [comment]
Bu soru bana biraz küme birleştirme konusunu ve Kruskal algoritmasını hatırlattı.
[Şu](https://github.com/spiralgo/algorithms/blob/master/src/main/java/algorithms/curated170/medium/ConnectingCitiesWithMinimumCost.java) soru öyle.

**Comment by altayhunoglu** [comment]
Evet.
Aynı şekilde, şu sorular da Kruskal'ın temeli olan Union-Find ile çözülebilir:
 
1101. The Earliest Moment When Everyone Become Friends
https://github.com/spiralgo/algorithms/issues/185

1061. Lexicographically Smallest Equivalent String
https://github.com/spiralgo/algorithms/issues/186
