### ISSUE TITLE
1055. Shortest Way to Form String

### ISSUE THREAD

**Issue by altayhunoglu** [spiralgo/algorithms#33]
https://leetcode.com/problems/shortest-way-to-form-string

Bize iki adet string veriliyor. 
Source: üzerinde işlem yapacağımız string.
Target: Source üzerinde işlem yapılarak elde etmemiz gereken String.

Source üzerinde işlemi, onun subsequence üretmek için yapacağız. 

Çünkü bu ürettiğimiz subsequenceleri birleştirerek Target değerine ulaşmamız gerekiyor.
Bize kaç tane "subsequence" üretilerek target değerine ulaşıldığı soruluyor.

Teknik açıklama:
Subsequence, substring'den farklıdır. 
Substring'de harfler arasında bir devamlılık söz konusudur. 
Örnek:
 "denizciler" kelimesi için "den" bir substringtir ve subsequence'tir. 
  Ama "dn" bir substring olmayıp, sâdece subsequence'tir.
   Çünkü "d, e, n" harflerinin devamlılığı bozulmuştur. 
 Bir subsequence, bir stringten bir veya birden fazla harf silinerek üretilebilr. Herhangi bir harf silmesek de bir string kendisinin subsequence'idir. 
 
 
![image](https://user-images.githubusercontent.com/60903744/118363632-f9c71980-b59d-11eb-8fd5-2bee010fd514.png)
![image](https://user-images.githubusercontent.com/60903744/118363658-0fd4da00-b59e-11eb-8d92-edfb688fd18d.png)

**Comment by ErdemT09** [comment]
Bu soruya da [bu konu](https://en.wikipedia.org/wiki/Finite-state_machine#Mathematical_model) bir biçimde ilişkili gibi.

**Comment by altayhunoglu** [comment]
> Bu soruya da [Finite-state machine konusu ve "formal alphabets"](https://en.wikipedia.org/wiki/Finite-state_machine#Mathematical_model) bir biçimde ilişkili gibi.

**- SPOILER ALERT-**

Evet. Bu soruda kabaca: hem kaynak metni hem hedef metni aynı anda gezmeye başlayan iki ayrı pointer kullanacağız.
Eğer kaynaktaki pointer ile hedefteki işaretçi aynı karakteri gösteriyorsa; iki işaretçiyi de ilerleteceğiz.
Aksi takdirde sadece kaynaktaki işaretçiyi ilerleteceğiz.
Eğer hedefteki işaretçi hiç ilerlememişse, bu kaynaktan o hedefi zaten oluşturamayız.
Bir kere bile olsa ilerlemişse, hedefteki kalan kısmı da gene kaynaktaki String'de ararız.

```
class Solution {
    public int shortestWay(String source, String target) {
        int t = 0;
        int ans = 0;
        while (t < target.length()) {
            int pt = t;
            
            for (int s = 0; s < source.length(); s++) {
                if (t < target.length() && source.charAt(s) == target.charAt(t)) {
                    t++;
                }
            }
            
            if (t == pt) {
                return -1;
            }
            ans++;
        }
        
        return ans;
    }
}
```

**Comment by ErdemT09** [comment]
Ben şöyle bir şeyle bir yöntem ürettim, seninki ama daha yalın duruyor.
```
public int shortestWay(String src, String target) {
            int p2 = 0;
            int procedures = 0;
            int prev = 0;
            while (p2 != target.length()) {
                  int p1 = 0;
                  while (p1 < src.length() && p2 < target.length()) {
                        if (src.charAt(p1) == target.charAt(p2)) {
                              p1++;
                              p2++;
                        } else {
                              p1++;
                        }
                  }

                  if (p2 == prev) {
                        return -1;
                  }

                  prev = p2;
                  procedures++;
            }
            return procedures;
      }
```

**Comment by ErdemT09** [comment]
PR açıp orada ayarlayayım.

**Comment by altayhunoglu** [comment]
Updated issue with images and the default code.
