### ISSUE TITLE
286. Walls and Gates

### ISSUE THREAD

**Issue by altayhunoglu** [spiralgo/algorithms#35]
https://leetcode.com/problems/walls-and-gates/

Burada, bir satranç tahtası gibi düşünülebilecek olan çok boyutlu bir array (int[][] rooms) veriliyor. 

Bu array içerisindeki elemanlar 3 çeşittir.

1- Wall: Bu bir duvar veya engel olarak düşünülebilir. (-1) integer değeri ile temsil edilir. Yani arrayin herhangi bir elemanı -1 ise, orada duvar vardır.

2-Gate: Bu Japon tarzı kapılara benzeyen bir yapı olarak düşünülebilir. Array'in herhangi bir elemanı 0 ise, orada bir gate vardır.

3- Empty room: Boş bir oda. Yani arrayin boş kısımları, içinde kapıya doğru yürünülecek bir koridor gibi düşünülebilir.
    Java'daki maximum Integer değeri ile temsil ediliyor. Yani arrayin herhangi bir elemanı, maximum integer değerine eşitse, orası boş bir odadır.

 Sorunun bizden istediği, herhangi bir boş odanın  "en yakınındaki kapıya" (the nearest gate) uzaklığı ile yani integer bir değer ile, wall hücrelerin -1 ile, gate hücrelerin 0 ile doldurulması.

**Comment by ErdemT09** [comment]
Solved:
https://github.com/spiralgo/algorithms/blob/master/src/main/java/algorithms/curated170/medium/WallsandGates.java
