### ISSUE TITLE
245. Shortest Word Distance III

### ISSUE THREAD

**Issue by altayhunoglu** [spiralgo/algorithms#36]
https://leetcode.com/problems/shortest-word-distance-iii

Burada, bir string listesi (wordsDict) veriliyor.
İki tane de ayrı string (word1, word2 ) veriliyor.
Bu stringlerin listede birbirlerine olan uzaklıklarını hesaplamamız isteniyor.
 
 Eğer herhangi bir sözcük listede tekrar ediyorsa, birden fazla uzaklık bulunacaktır. 
 Bizden istenen en kısa uzaklığı bulmamız.

 Not: word1 ve word2 aynı stringe eşit olabilir.

Input: wordsDict = ["practice", "makes", "perfect", "coding", "makes"], 
word1 = "makes", word2 = "coding"
Output: 1

**Comment by ErdemT09** [comment]
Düşününce 2 kelimenin aynı olup olmadığına bakıp öyleyse aynı öğrenin bir listede en kısa ne zaman tekrar ettiğine ayrı bir biçimde bakmak da var.
Ama 2 farklı işlemi bir arada yapabiliecek bir yöntem gerek. Böylece zeka istemeli, yoksa fazla kolay olur. Mülakatta sorulsa o yanıt ve ona doğru olan problem çözme süreci incelenirdi zaten.

**Comment by altayhunoglu** [comment]
> Düşününce 2 kelimenin aynı olup olmadığına bakıp öyleyse aynı öğrenin bir listede en kısa ne zaman tekrar ettiğine ayrı bir biçimde bakmak da var.
> Ama 2 farklı işlemi bir arada yapabiliecek bir yöntem gerek. Böylece zeka istemeli, yoksa fazla kolay olur. Mülakatta sorulsa o yanıt ve ona doğru olan problem çözme süreci incelenirdi zaten.

### SPOILER 
Haklısın. Aynı olup olmadığına gene bakacağız ve if-else içinde bunu kontrol edeceğiz.
İlk kelimenin bulunduğu inekse index1 diyelim. İkincisine ise index2 diyelim.

- Aynı olma durumunda:

İki kelime aynı ise, **ikinci** (veya birden fazla) kez o kelime ile karşılaştığı nokta, aynı zamanda diğer denemeler için **ilk** index olacaktır.
Döngüyü pointer diye bir index ile kurduğumuzu düşünelim:

 ```
index1 = index2;
 index2 = pointer;
```
 
 - Farklı olma durumunda ise:
   Eğer bulunan kelime ilki ise:
` index1= pointer;`
    Eğer bulunan kelime ikinci ise:
` index2 = pointer;`
 
  ... diyerek aramayı sürdüreceğiz.

**Comment by ErdemT09** [comment]
Solved:
https://github.com/spiralgo/algorithms/tree/master/src/main/java/algorithms/curated170/medium/shortestworddistance3
