### ISSUE TITLE
348. Design Tic-Tac-Toe

### ISSUE THREAD

**Issue by altayhunoglu** [spiralgo/algorithms#37]
https://leetcode.com/problems/design-tic-tac-toe

  Tic-Tac-Toe, bizim Türkiye'de oynadığımız SOS oyununa benziyor. 
 
  Ama bir oyuncu X taşını seçti ise, diğeri de O taşını seçmiştir ve bu taşlar artık değiştirilemez.

 Burada bizden, TicTacToe  diye bir sınıf tasarlamamız isteniyor.
 
Bu sınıftaki metodlar:
  int move(int row, int col, int player): 
  hangi oyuncunun, hangi satır ve sütuna kendi taşını koyduğunu belirten hamle.
 Bir hamle yapıldıktan sonra şu üç sonuç gerçekleşebilir:
                0:  kimse kazanamaz (oyun devam eder)
                1:  ilk oyuncu kazanır
                2: ikinci oyuncu kazanır

Daha ayrıntılı bilgi için, verilen örneği incelemek daha iyi olacaktır:
https://leetcode.com/problems/design-tic-tac-toe/

**Comment by ErdemT09** [comment]
Solved:
https://github.com/spiralgo/algorithms/blob/master/src/main/java/algorithms/curated170/medium/DesignTicTacToe.java
