### ISSUE TITLE
1060. Missing Element in Sorted Array

### ISSUE THREAD

**Issue by altayhunoglu** [spiralgo/algorithms#38]
https://leetcode.com/problems/missing-element-in-sorted-array

 Bir integer array (int[] num) veriliyor.
 Bu array, artan sıradadır (ascending order) ve her bir eleman diğerlerinden farklıdır (unique)
  
 Bu array, artan sıradadır ama arada bazı rakamlar eksik olabilir. Yani birer birer artmaz.
Bu yüzden missingElement(int[] nums, int k) içerisinde bir de "k" sayısı verilmiş.
 Bize, soldan başlayarak bakacak olursak, k. kayıp elemanı bulmamız isteniyor. 
 Yani k= 3 ise, kayıp elemanlar içerisinde üçüncüsü isteniyor.

Örnek:

 Input: nums = [4,7,9,10], k = 1
 k= 1 olduğu için, kayıp sayılar arasındaki birincisi isteniyor.

 Eğer bu array, birer birer artsa idi şöyle olurdu:
 nums = [4, **5**, 6, 7, 8, 9,10],

 Dolayısı ile, birinci kayıp rakam 5'dir. Bu sonuç gösterilir.
 
 Varsayılan kod:
```
 class Solution {
    public int missingElement(int[] nums, int k) {
        
    }
} 
```
 
![image](https://user-images.githubusercontent.com/60903744/118363524-75749680-b59d-11eb-9ca8-bb52d6bf5b14.png)

![image](https://user-images.githubusercontent.com/60903744/118363572-b2408d80-b59d-11eb-82f9-ec868fa2e6b1.png)

**Comment by ErdemT09** [comment]
Solved:
https://github.com/spiralgo/algorithms/blob/master/src/main/java/algorithms/curated170/medium/DesignTicTacToe.java

**Comment by altayhunoglu** [comment]
Updated the issue with the default code and the images.
