### ISSUE TITLE
362. Design Hit Counter

### ISSUE THREAD

**Issue by altayhunoglu** [spiralgo/algorithms#4]
Burada, meselâ bir Web sayfasına gelebilecek "hit" sayısını tutan bir sınıf tasarlayacağız.
  hit(int timestamp): methodu ile, depoya bir hit ekleyeceğiz. Depoyu bir ArrayList olarak düşünebiliriz. Buna karar vermek bize kalmış.
   
 Buradaki "timestamp" o hitin geldiği saniyeyi gösteriyor. 

int getHits(int timestamp): timestamp ile belirtilen saniyeye kadar gelen tüm hit sayısı gösterilecek.

**Comment by ErdemT09** [comment]
Solved: 
https://github.com/spiralgo/algorithms/tree/master/src/main/java/algorithms/curated170/medium/designahitcounter
