### ISSUE TITLE
1066. Campus Bikes II

### ISSUE THREAD

**Issue by altayhunoglu** [spiralgo/algorithms#41]
Bu soru, https://github.com/altayhunoglu/algorithms/issues/32 linkinde anlatılan soru ile benzerdir.
Bu sefer, her bir işçinin aldığı bisikletin indexi değil, işçiler ile bisikletler arasındaki minimum toplam mesafe isteniyor.

LeetCode Linki:
https://leetcode.com/problems/campus-bikes-ii/

**Comment by ErdemT09** [comment]
Bu soru önceki sorundan fazla biraz Traveling Salesperson gibi.

**Comment by ErdemT09** [comment]
It's easy to understand when one understands what the bit manipulations here mean.
