### ISSUE TITLE
256. Paint House

### ISSUE THREAD

**Issue by altayhunoglu** [spiralgo/algorithms#44]
https://leetcode.com/problems/paint-house

 n sayıda ev olduğunu düşün.
 bu evleri 3 renkten (Red, Blue, Green) biri ile boyayacaksın.
 Ama meselâ birinci evi mavi ile boyamak ile ikinci evi mavi ile boyamanın maliyetleri farklı olabilir.
 Yani bazı renkler, bazı evlere daha uygun maliyettedir.

Bu evleri, hiçbir bitişik (adjacent) iki ev aynı renkten olmayacak şekilde boyamak gerekiyor.

Bize sorulan şey, tüm evleri en düşük (minimum) mâliyet ile boyamak için gereken tutardır.

(Yani hangi evi hangi renge boyadığımızın listesini değil, toplam mâliyeti istiyor.
Burada, "minimum" bize ya Greedy stratejiyi ya da Dynamic Programming'i hatırlatmalı idi.)

Örnek:
Input: costs = [[17,2,17],[16,16,5],[14,3,19]]

[17,2,17]: Burada ilk 17 birinci evi Red ile boyamanın maliyeti, 2 Blue ile boyamanın maliyeti, 17 ise Green ile boyamanın maliyeti.
[16,16,5]: Burada ilk 16 ikinci evi Red ile boyamanın maliyeti, ikinci 16 Blue ile boyamanın maliyeti, 5 ise Green ile boyamanın maliyeti.
,[14,3,19]]: Burada ilk 14 üçüncü evi Red ile boyamanın maliyeti,  3 Blue ile boyamanın maliyeti, 19 ise Green ile boyamanın maliyeti.
Dolayısı ile:

ilk evi : Blue ile boyanırsa maliyet 2 olur.
ikinci ev: Green ile boyanırsa maliyet 5 olur.
üçüncü ev: Blue ile boyanırsa maliyet 3 olur.
 
Minimum maliyet: 10 bulunmuş olur.

Burada üç ev için sonuç bulduk. Ama ev sayısı (n) çok büyük olduğunda işler daha zorlaşacağı için, buna uygun algoritma geliştirmemiz isteniyor.

**Comment by ErdemT09** [comment]
Bunun için olan eder birikmeli (accumulating) algoritmayı şöyle görselleştirebiliriz:
![paintHouse](https://user-images.githubusercontent.com/63192680/115111455-28df7080-9f89-11eb-80a4-638fcfb0a3a3.jpg)

**Comment by altayhunoglu** [comment]
Selâmlar Erdem,
 Çizim çok aydınlatıcı olmuş, eline sağlık.
 
 Kod da çok güzel ve açık.
 Küçük bir önerim olacak. 
 "h-1" işlemlerinden kurtulmak yaklaşık 1 ms kadar hızlandırır.
 
 ```
public class Solution {
    static int minCost(int[][] costs)
    {
        int h = costs.length-1; //number of houses
 
        for(int i = 1; i<=h;i++)
        {
            costs[i][0] += Math.min(costs[i-1][1], costs[i-1][2]);
            costs[i][1] += Math.min(costs[i-1][2], costs[i-1][0]);
            costs[i][2] += Math.min(costs[i-1][0], costs[i-1][1]);
        }
        return Math.min(Math.min(costs[h][0], costs[h][1]), costs[h][2]);
    }
  
      
}
```

**Comment by altayhunoglu** [comment]
Son şekli ile ekleyip merge ettim. Remote branchi sildim.

**Comment by ErdemT09** [comment]
Solved:
https://github.com/spiralgo/algorithms/blob/master/src/main/java/algorithms/curated170/medium/PaintHouse.java
