### ISSUE TITLE
250. Count Univalue Subtrees

### ISSUE THREAD

**Issue by altayhunoglu** [spiralgo/algorithms#45]
https://leetcode.com/problems/count-univalue-subtrees/

Bir binary tree veriliyor.   (Bu bir Binary Search Tree olmadığı için, root'un solundakiler kendisinden küçük olmak zorunda değil)

uni-value olan node'ların sayısı isteniyor. 
uni-value: her biri aynı değere sahip olan node'lar.

Varsayılan kod:
```
class Solution {
    public int countUnivalSubtrees(TreeNode root) {
        
    }
}

```
![image](https://user-images.githubusercontent.com/60903744/120088172-be2c6380-c0f6-11eb-9055-c05074f503dd.png)
![image](https://user-images.githubusercontent.com/60903744/120088174-c5537180-c0f6-11eb-8a19-c15b0ae17a58.png)

**Comment by ErdemT09** [comment]
Solved:
https://github.com/spiralgo/algorithms/tree/master/src/main/java/algorithms/curated170/medium/countunivaluesubtrees
