### ISSUE TITLE
651. 4 Keys Keyboard

### ISSUE THREAD

**Issue by altayhunoglu** [spiralgo/algorithms#47]
https://leetcode.com/problems/4-keys-keyboard

 Sadece 4 tuşu olan özel bir klavyen olduğunu düşün.
 Bu klavyede sadece 4 tane işlem yapabiliyorsun.
 1-  "A" harfine basabilirsin
 2- (Ctrl-A) ile, şu ana kadar yazılmış olan her şeyi seçebilirsin
 3- (Ctrl-C) ile, seçilen kısmı kopyalayabilirsin.
 4- (Ctrl-V) ile, kopyalanan kısmı yapıştırabilirsin.

Bu soruda sana bir de N sayısı verilebilir. Yani, bu tuşlara basabilme hakkı.
İşte bu 4 tuş kullanarak ve en fazla N kadar basarak yazabileceğin maksimum A sayısı isteniyor. 

Varsayılan kod:

```
class Solution {
    public int maxA(int n) {
        
    }
}
```
![image](https://user-images.githubusercontent.com/60903744/120101238-ce236200-c14d-11eb-9044-c2999d307d59.png)
![image](https://user-images.githubusercontent.com/60903744/120101245-d54a7000-c14d-11eb-9681-f363d36dc151.png)

**Comment by ErdemT09** [comment]
2-3-4 tek işlem değil mi? Öbür türlü karlı olamaz.

**Comment by altayhunoglu** [comment]
Issue has been updated with images and the default code.

**Comment by ErdemT09** [comment]
Bu sorunun güzel bir matematiği var. Mantığını içten anlamak için gerekli bence.
