### ISSUE TITLE
490. The Maze

### ISSUE THREAD

**Issue by altayhunoglu** [spiralgo/algorithms#48]
https://leetcode.com/problems/the-maze

 Burada bir labirent (maze) veriliyor. int[][] maze arrayi ile gösteriliyor.
 Labirent'in boşlukları 0 ile, duvarları 1 ile temsil ediliyor. 

 Bir topu, belirtilen hedef noktasına; sağ-sol, yukarı-aşağı işlemleri ile taşımaya çalışacağız.
 Burada anlaşılması gereken nokta, örneğin "aşağı" işlemi bir kez yapılırsa, top sürekli aşağı düşecek, tâ ki bir duvar ile karşılaşana kadar.
 Dolayısı ile, topu target'a taşımanın mümkün olup olmadığı soruluyor.

**Comment by ErdemT09** [comment]
Solved:
https://github.com/spiralgo/algorithms/blob/master/src/main/java/algorithms/curated170/medium/SortTransformedArray.java
