### ISSUE TITLE
280. Wiggle Sort

### ISSUE THREAD

**Issue by altayhunoglu** [spiralgo/algorithms#5]
Burada bir integer array veriliyor. Bu array herhangi bir sırada olmayıp rastgele dizilmiş.
 nums = [3,5,2,1,6,4]
Bu arrayi, öyle şu şekilde sıralamanız isteniyor: 

**nums[0] <= nums[1] >= nums[2] <= nums[3]...**

Mesela buna uyacak şekilde şöyle sıralanabilir:
3 <= 5 >= 1 <= 6 >= 2 <= 4  olduğundan, **sonuç :  [3,5,1,6,2,4]**

https://leetcode.com/problems/wiggle-sort/

**Comment by ErdemT09** [comment]
Solved:
https://github.com/spiralgo/algorithms/blob/master/src/main/java/algorithms/curated170/medium/WiggleSort.java
