### ISSUE TITLE
360. Sort Transformed Array

### ISSUE THREAD

**Issue by altayhunoglu** [spiralgo/algorithms#52]
https://leetcode.com/problems/sort-transformed-array/

Bu soruda öncelikle şu fonksiyonu java ile yazacağız:
 f(x) = ax2 + bx + c
 (Bu a, b, c değerleri sortTransformedArray methoduna parametre olarak gönderilmiş.)
 
Daha sonra, bu fonksiyonu, int[] nums arrayi içerisindeki her bir elemana uygulayacağız.
Bu nums arrayi başlangıçta sıralı idi. Sonuçta oluşacak arrayin de aynı şekilde sıralı olması isteniyor.

Örnek:
Input: nums = [-4,-2,2,4], a = 1, b = 3, c = 5
Output: [3,9,15,33]

**Comment by ErdemT09** [comment]
Solved:
https://github.com/spiralgo/algorithms/blob/master/src/main/java/algorithms/curated170/medium/SortTransformedArray.java
