### ISSUE TITLE
1429. First Unique Number

### ISSUE THREAD

**Issue by altayhunoglu** [spiralgo/algorithms#53]
Bir kuyruk (queue) var.
 FirstUnique ile biz bu kuyruğu tasarlayacağız.
(Değerleri depolamak için Java'daki Queue sınıfı kullanılabileceği gibi bir array de kullanılabilir.)
Bu kuyruk integer değerlerden oluşuyor.
Bu kuyruğa add metodu ile her an yeni bir değer eklenebilmeli.
showFirstUnique metodu ile de, o kuyrukta rastlanılan ilk biricik (unique, tekrar etmeyen) değer gösterilmeli.

https://leetcode.com/problems/first-unique-number/

**Comment by ErdemT09** [comment]
Solved:
https://github.com/spiralgo/algorithms/tree/master/src/main/java/algorithms/curated170/medium/firstunique
