### ISSUE TITLE
259. 3Sum Smaller

### ISSUE THREAD

**Issue by altayhunoglu** [spiralgo/algorithms#55]
https://leetcode.com/problems/3sum-smaller

Bir integer arrayi (int[] nums) ve bir hedef değer (int target) veriliyor.

Şu şartları sağlayacak üçlülerin sayısı isteniyor:
i, j, k bu üçlünün indeksleri olsun:  (0 <= i < j < k < n  olmak üzere)
nums[i] + nums[j] + nums[k] < target şartına uygun üçlüleri listeleyeceğiz.

(Burada n, nums içindeki eleman sayısı. Bununla birlikte toplama elemanlarının yeri değişebilir (commutative) olduğundan, buradaki 0 <= i < j < k < n ifâdesinin tek maksadı, muhtemelen, aynı elemanı iki kez toplamayı engellemek içindir. Yani; i, j, k indekslerinin sırasını değiştirmek toplamayı değiştirmez. Bu bize, orijinal diziyi sıralayabileceğimizi gösterir.)
 
Varsayılan kod:
```
class Solution {
    public int threeSumSmaller(int[] nums, int target) {
        
    }
}
```

![image](https://user-images.githubusercontent.com/60903744/117369696-f19c1980-aecd-11eb-8487-91abc3c3cbdd.png)

**Comment by ErdemT09** [comment]
https://www.github.com/spiralgo/algorithms/tree/master/src%2Fmain%2Fjava%2Falgorithms%2FSubsetSum.java
Confer the HashMap solution.

**Comment by ErdemT09** [comment]
Buradaki her sayı bir kez mi çıkıyor yoksa birden fazla çıkabiliyor mu?

**Comment by altayhunoglu** [comment]
> Buradaki her sayı bir kez mi çıkıyor yoksa birden fazla çıkabiliyor mu?

`0 <= i < j < k < n` den ötürü öyle olsa gerek. Buna dair bir constraint belirtmemiş ama bunun doğal sonucu sayabiliriz.
