### ISSUE TITLE
247. Strobogrammatic Number II

### ISSUE THREAD

**Issue by altayhunoglu** [spiralgo/algorithms#57]
https://leetcode.com/problems/strobogrammatic-number-ii

Strobogrammatic Number: 180 derece ters çevrildiğinde, gene de aynı kalan sayı demektir.

Bize bir "n" değeri veriliyor. "n" basamaklı tüm strobogrammatic sayıları bir String listesinde döndürmemiz isteniyor.

Varsayılan kod:
```
class Solution {
    public List<String> findStrobogrammatic(int n) {
        
    }
}

```
![image](https://user-images.githubusercontent.com/60903744/117370772-90754580-aecf-11eb-9657-007a41c1c0d4.png)

**Comment by ErdemT09** [comment]
This is a Fibonacci-like question, for n=k, we have to mix k-2 and k-3. That's how it can be constructed but I'm not sure how.

**Comment by altayhunoglu** [comment]
> This is a Fibonacci-like question, for n=k, we have to mix k-2 and k-3. That's how it can be constructed but I'm not sure how.

I think you are on the right track. It means it can be solved recursively or iteratively (using dynamic programming?).

I can provide the patterns for you:

```
Input: n = 0
 [ ]

Input: n = 1
 ["0","1","8"]
 
Input: n = 2
 ["11","69","88","96"]

Input: n = 3:
["101","111","181","609","619","689","808","818","888","906","916","986"]

Input: n = 4:
["1001","1111","1691","1881","1961","6009","6119","6699","6889","6969","8008","8118","8698","8888","8968","9006","9116","9696","9886","9966"]

...
...

Input: n = 9:
["100000001","100010001","100080001","100101001","100111001","100181001","100609001","100619001","100689001","100808001","100818001","100888001","100906001","100916001","100986001","101000101","101010101","101080101","101101101","101111101","101181101","101609101","101619101","101689101","101808101","101818101","101888101","101906101","101916101","101986101","106000901","106010901","106080901","106101901","106111901","106181901","106609901","106619901","106689901","106808901","106818901","106888901","106906901","106916901","106986901","108000801","108010801","108080801","108101801","108111801","108181801","108609801","108619801","108689801","108808801","108818801","108888801","108906801","108916801","108986801","109000601","109010601","109080601","109101601","109111601","109181601","109609601","109619601","109689601","109808601","109818601","109888601","109906601","109916601","109986601","110000011","110010011","110080011","110101011","110111011","110181011","110609011","110619011","11...

```

**Comment by ErdemT09** [comment]
Actually, the left side of such a number can be mirrored to he right. The left side is just the permutation of the digits 0,1,6,8,9. This might result in some backtracking algorithm instead.
