### ISSUE TITLE
487. Max Consecutive Ones II

### ISSUE THREAD

**Issue by altayhunoglu** [spiralgo/algorithms#59]
https://leetcode.com/problems/max-consecutive-ones-ii/

Bir binary array (yani tüm değerleri 0 veya 1'lerden oluşan int[] nums arrayi) veriliyor.

Bu array'de "yalnızca bir adet" 0 değerini 1'e dönüştürme (flip) hakkı verilse, bu hakla oluşturabileceğiniz en uzun 1'ler dizisinin uzunluğu ne olurdu? 

Varsayılan kod:
```
class Solution {
    public int findMaxConsecutiveOnes(int[] nums) {
        
    }
}
```
![image](https://user-images.githubusercontent.com/60903744/117371623-df6faa80-aed0-11eb-9e0b-77303f70af78.png)

**Comment by ErdemT09** [comment]
Count left side of the 0 and the right side.
When a second 0 is seen compare left+right+1 with the max and make the right the new left.
