### ISSUE TITLE
1236. Web Crawler

### ISSUE THREAD

**Issue by altayhunoglu** [spiralgo/algorithms#6]
Burada, arama motorlarının "crawler" denilen mekanizmasını simüle eden bir sistem tasarlayacağız.
 Bu sistem bazen "örümcek" olarak da adlandırılır. 
 Bir url altındaki tüm linkleri toplar. Buna "crawl" etmek diyelim.
 Bunu simule etmek için soruda HtmlParser denilen bir parser verilmiş.
 
  Gûyâ, ona url parametresi ile bir link ona gönderildiğinde, bize o link altındaki tüm url'lerin listesini o gönderecek.
```
 interface HtmlParser {
       public List<String> getUrls(String url) {}
  }
```
Bizim tarafımızda ise, şu kod implement edilmeli:
```
  public List<String> crawl(String startUrl, HtmlParser htmlParser) {
        
    }
```

Dikkat edilecek hususlar:
- startUrl ile belirtilen sayfadan başlanmalı.
- Verilen web sayfasının altındaki tüm linkleri çekmek için HtmlParser.getUrls(url) çağrılmalı.
- Aynı link birden fazla kez "crawl" edilmeyecek. 
- Sâdece startUrl ile aynı url altındaki linkleri tara.

![image](https://user-images.githubusercontent.com/60903744/117521108-b6284a80-afb4-11eb-90ef-ae4d0a111be1.png)
![image](https://user-images.githubusercontent.com/60903744/117521112-c04a4900-afb4-11eb-9b3e-69eece650920.png)
![image](https://user-images.githubusercontent.com/60903744/117521121-cc360b00-afb4-11eb-95cf-4c7f72dcb4da.png)
![image](https://user-images.githubusercontent.com/60903744/117521129-d821cd00-afb4-11eb-9cef-d68c6234930f.png)
![image](https://user-images.githubusercontent.com/60903744/117521133-df48db00-afb4-11eb-8b21-70721a96b3c3.png)
![image](https://user-images.githubusercontent.com/60903744/117521140-e7087f80-afb4-11eb-8136-cc62f7632c77.png)
![image](https://user-images.githubusercontent.com/60903744/117521142-eec82400-afb4-11eb-88e6-cfc074ab846e.png)
![image](https://user-images.githubusercontent.com/60903744/117521144-f4be0500-afb4-11eb-97ba-4b8888b6e0a1.png)

**Comment by ErdemT09** [comment]
Is this the solution? https://github.com/spiralgo/algorithms/blob/master/src/main/java/algorithms/Solution.java

**Comment by altayhunoglu** [comment]
Yep. That is one of the possible solutions.

**Comment by ErdemT09** [comment]
We should move it to the [curated170 folder](https://github.com/spiralgo/algorithms/tree/master/src/main/java/algorithms/curated170) then.

**Comment by altayhunoglu** [comment]
You are right.

**Comment by altayhunoglu** [comment]
> Is this the solution? https://github.com/spiralgo/algorithms/blob/master/src/main/java/algorithms/Solution.java

Özür dilerim, buradaki sâdece bir taslaktan ibaretmiş.
Gerçek çözümü ekleyip PR açtım.
https://github.com/spiralgo/algorithms/pull/178

**Comment by ErdemT09** [comment]
Solved:
https://github.com/spiralgo/algorithms/blob/master/src/main/java/algorithms/curated170/medium/WebCrawlerQueue.java
