### ISSUE TITLE
254. Factor Combinations

### ISSUE THREAD

**Issue by altayhunoglu** [spiralgo/algorithms#60]
https://leetcode.com/problems/factor-combinations

Burada "factor" dediği, bir sayının çarpanları demektir.
8 = 2 x 2 x 2 şeklinde yazılabilirdi.
  = 2 x 4 şeklinde de yazılabilirdi. Dolayısı ile, 8'in çarpan kombinasyonlarına bu ikisi de dahildir. 

Varsayılan kod:
```
class Solution {
    public List<List<Integer>> getFactors(int n) {
        
    }
}
```

Burada bizden, bir sayının tüm çarpan kombinasyonları isteniyor.
![image](https://user-images.githubusercontent.com/60903744/117371737-0fb74900-aed1-11eb-8815-f3b8a662979d.png)
![image](https://user-images.githubusercontent.com/60903744/117371818-32496200-aed1-11eb-91ad-e2a1e7741dee.png)

**Comment by ErdemT09** [comment]
İnternette buna bulduğum çözümler neredeyse brute-force'umsu bir biçimde sayıya veya köküne kadar tüm sayılarla bölünmesine bakıyorlar. Acaba bunun yerine sayının asal çarpanlarını bulup onları sayıp saymama durumuna göre #43 'deki gibi bir backtraking'le çözmek daha verimli olabilir mi?

**Comment by altayhunoglu** [comment]
Tabii, neden olmasın. Deneriz.

**Comment by ErdemT09** [comment]
Asal çarpanlarına ayırıp yapmak ya çok verimsiz ya da karmaşık bir şeye yol açabiliyor, öbür çözümlere bakılmalı. En azından artık burada asal çarpanlarına ayırma algoritması var.
