### ISSUE TITLE
325. Maximum Size Subarray Sum Equals k

### ISSUE THREAD

**Issue by altayhunoglu** [spiralgo/algorithms#61]
https://leetcode.com/problems/maximum-size-subarray-sum-equals-k

Bir integer arrayi int[] nums ve integer k değeri veriliyor.
Nums içinde, elemanlarının toplamı k değerine eşit olan en uzun sub-array'in uzunluğu isteniyor.

Örnek:
Input: nums = [1, -1, 5, -2, 3], k = 3
Output: 4 
Explanation: Bu subarray'deki [1, -1, 5, -2] elemanlarının toplamı 3'e eşit. 3'e eşit olan subarrayler arasındaki en uzunu da bu olduğu için, cevap 4. (bu arrayin uzunluğu)

Varsayılan kod:
```
class Solution {
    public int maxSubArrayLen(int[] nums, int k) {
        
    }
}
```

![image](https://user-images.githubusercontent.com/60903744/117372022-894f3700-aed1-11eb-917b-9e618e60e4ef.png)
![image](https://user-images.githubusercontent.com/60903744/117372045-953af900-aed1-11eb-9e48-6bdd20a091ec.png)

**Comment by ErdemT09** [comment]
Basically subset sum but with a bit more restrictions.

**Comment by altayhunoglu** [comment]
> Basically subset sum but with a bit more restrictions.

You are right.
