### ISSUE TITLE
549. Binary Tree Longest Consecutive Sequence II

### ISSUE THREAD

**Issue by altayhunoglu** [spiralgo/algorithms#62]
Burada, istenen şey bir Binary Tree'deki en uzun yollar "ardışık elemanlı" array isteniyor.
Bu sefer ardışık (Consecutive) olma durumu artan sırada da azalan sırada da olabilir. Parent'tan child'a olabilir veyâ tam tersi de olabilir. Child-parent-child yolunu da izleyebilir.

Örnekler incelenmeli:
https://leetcode.com/problems/binary-tree-longest-consecutive-sequence-ii/

![image](https://user-images.githubusercontent.com/60903744/121430035-4117ae80-c980-11eb-989a-864433dca9a2.png)
![image](https://user-images.githubusercontent.com/60903744/121430060-496fe980-c980-11eb-99ff-e016d82a7c2e.png)

**Comment by ErdemT09** [comment]
![image](https://user-images.githubusercontent.com/63192680/121470957-97f4a680-c9c7-11eb-8a42-dcc632e08ca5.png)
