### ISSUE TITLE
314. Binary Tree Vertical Order Traversal

### ISSUE THREAD

**Issue by altayhunoglu** [spiralgo/algorithms#63]
Bir Binary Tree'nin dikey sıralaması isteniyor.
Dikey sıralama, deep-first'ten farklı.
Ağaca baktığında, üst ağaçtaki bir node ile, aşağılardaki bir ağaç aynı kolonda hizalanabiliyor. 
İşte aynı kolonda hizalanmaları listeleyeceğiz.
Örnekler gayet açıklayıcı olduğu için incelenmeli:
https://leetcode.com/problems/binary-tree-vertical-order-traversal/

Varsayılan kod:
```
class Solution {
    public List<List<Integer>> verticalOrder(TreeNode root) {
        
    }
}
```

![image](https://user-images.githubusercontent.com/60903744/117374590-1b593e80-aed6-11eb-93eb-460f2b82e795.png)
![image](https://user-images.githubusercontent.com/60903744/117374598-23b17980-aed6-11eb-86f8-a3f828037db0.png)
![image](https://user-images.githubusercontent.com/60903744/117374612-2ad88780-aed6-11eb-9dbe-5d2299186aa4.png)

![image](https://user-images.githubusercontent.com/60903744/117374668-3af06700-aed6-11eb-8cd2-c142067e04ef.png)

**Comment by ErdemT09** [comment]
In which column is this node?
![image](https://user-images.githubusercontent.com/63192680/121473365-3cc4b300-c9cb-11eb-97fb-303547f1a040.png)

**Comment by altayhunoglu** [comment]
When I use tree-visualizer on LeetCode:

![image](https://user-images.githubusercontent.com/60903744/121491372-8e2a6d80-c9de-11eb-8064-c9cb62ad52e5.png)

![IMG-1659](https://user-images.githubusercontent.com/60903744/121491526-b31ee080-c9de-11eb-83f4-bf92642ea1a3.jpg)
