### ISSUE TITLE
562. Longest Line of Consecutive One in Matrix

### ISSUE THREAD

**Issue by altayhunoglu** [spiralgo/algorithms#68]
0 ve 1'lerden oluşan bir çok boyutlu array, yani matrix veriliyor.
Matrix'teki 1'leri birleştirebilecek en uzun çizgi kaç birimdir? diye soruyor.
Bu çizgi, yatay-dikey-çapraz olabilir.

https://leetcode.com/problems/longest-line-of-consecutive-one-in-matrix/

Varsayılan kod:
```java
class Solution {
    public int longestLine(int[][] mat) {
        
    }
}
```

![image](https://user-images.githubusercontent.com/60903744/121812288-f479ef00-cc6f-11eb-959e-325df8c851b4.png)
![image](https://user-images.githubusercontent.com/60903744/121812297-fb086680-cc6f-11eb-816c-b17374897253.png)

**Comment by ErdemT09** [comment]
DFS or BFS can be useful.
