### ISSUE TITLE
261. Graph Valid Tree

### ISSUE THREAD

**Issue by altayhunoglu** [spiralgo/algorithms#76]
https://leetcode.com/problems/graph-valid-tree

 validTree(int n, int[][] edges) fonksiyonu içerisinde n= node sayısı, edges ise bu node'ların birbirleri ile olan bağlantılarını içeriyor.

Verilen n ve edges'in, geçerli bir ağaç oluşturup oluşturmadığı soruluyor.

Varsayılan kod:
```
class Solution {
    public boolean validTree(int n, int[][] edges) {
        
    }
}
```

![image](https://user-images.githubusercontent.com/60903744/119341414-6330e180-bc9c-11eb-9842-138f06edc2da.png)
![image](https://user-images.githubusercontent.com/60903744/119341425-69bf5900-bc9c-11eb-913e-ba7af2fcedc0.png)
![image](https://user-images.githubusercontent.com/60903744/119341456-72b02a80-bc9c-11eb-8585-b05ea0513730.png)

**Comment by ErdemT09** [comment]
Başka deyişle döngü olup olmadığına bakmalıyız.

**Comment by altayhunoglu** [comment]
> Başka deyişle döngü olup olmadığına bakmalıyız. Disjoint set sorusu.

Evet haklısın Erdem. 
The issue has been updated with images and the default code.

**Comment by ErdemT09** [comment]
A tree is what a tree cannot be. It is a connected and directed acyclic graph with indegree of every node besides some root being 1.
![image](https://user-images.githubusercontent.com/63192680/122445263-0b8b4a80-cfaa-11eb-869d-6f7d751dc81d.png)
https://en.wikipedia.org/wiki/Tree_(data_structure)#Preliminary_definition
