### ISSUE TITLE
484. Find Permutation

### ISSUE THREAD

**Issue by altayhunoglu** [spiralgo/algorithms#8]
Burada, sadece iki harf kullanılarak gösterilen bir şifre veriliyor ve bu şifreyi çözmemiz isteniyor.
İki harf şunlar:

(1)
D: İngilizce "decrease" (azalan) kelimesinin baş harfi. Yani bununla temsil edilen iki rakam arasında "azalan" ilişkisi varmış. 
 örnek: "D": [2, 1]  
 Çünkü 2 ile 1 arasında azalma ilişkisi vardır. Burada örneğin "D": [4, 3] olduğunu da düşünebilirdik ama, soru bizden minimum rakamları kullanmamızı bekliyor.
 Bu arada, bir kere kullanılan rakam bir daha kullanılamaz. 
 
(2)
I: İngilizce "increase" (artan) kelimesinin baş harfi. Yani bununla temsil edilen iki rakam arasında "artan" ilişkisi varmış. 
Örnek: "I": [1,2]
Çünkü 1 ile 2 arasında artan ilişkisi vardır. Burada da örneğin "I": [6, 7] olduğunu da düşünebilirdik ama, soru bizden minimum rakamları kullanmamızı bekliyor.

Son olarak, hem I hem de D'yi aynı anda içeren bir örnek:
Input: "DI"
Sonuç: [2,1,3]

Burada, sonuç [3,1,2] da olabilirdi ama bizden sözlük sırası bakımından (lexicographical) en küçük sonuç isteniyor.

**Comment by ErdemT09** [comment]
En temel input olarak yalnız I'lerden oluşan bir String düşünülebilir.
IIIIIIII (8 tane I) verildiğinde doğal bir biçimde artan bir çıktımız olmalı:  [1,2,3,4,5,6,7,8,9] 
Araya 3 tane 'D' koyalım: IIIIDDDI => çıktı 123487659 olmalı. 
Burada fark edilecek şey şu: D olan aralıklarda sayı sırası olması gerekenin tersine dönüşür.

**Comment by ErdemT09** [comment]
Solved:
https://github.com/spiralgo/algorithms/tree/master/src/main/java/algorithms/curated170/medium/findpermutation
