### ISSUE TITLE
276	 Paint Fence

### ISSUE THREAD

**Issue by altayhunoglu** [spiralgo/algorithms#81]
https://leetcode.com/problems/paint-fence/

Çit boyama sorusu.
Çit'in "n" adet direği var.
"k" adet renk seçilebilir.

Şu şartlara göre boyama yapılacak:
-Her çit, sadece 1 renk ile boyanacak.
-Sâdece 1 çift (yani iki tane) komşu aynı renk olabilir.

Bizden, mümkün olan tüm boyama yollarının sayısını istiyor.

Varsayılan kod:
```java
class Solution {
    public int numWays(int n, int k) {
        
    }
}
```

![image](https://user-images.githubusercontent.com/60903744/120464880-16d55800-c3a6-11eb-8eeb-5635fca59c54.png)
![image](https://user-images.githubusercontent.com/60903744/120464912-1e94fc80-c3a6-11eb-99e9-20b67913fbb8.png)

**Comment by ErdemT09** [comment]
Solved:
https://github.com/spiralgo/algorithms/blob/master/src/main/java/algorithms/curated170/medium/PaintFence.java
