### ISSUE TITLE
267. Palindrome Permutation II

### ISSUE THREAD

**Issue by altayhunoglu** [spiralgo/algorithms#83]
Palindrome, tersten yazıldığında kendisine eşit olan kelime demektir.
Örnek: Kazak, Nalan, Talat gibi.

Bize bir string veriliyor. Bu stringin harfleri ile üretilebilecek (ve string ile aynı uzunlukta olan) tüm palindrome'ların listesi isteniyor.

https://leetcode.com/problems/palindrome-permutation-ii/

Varsayılan kod:
```java
class Solution {
    public List<String> generatePalindromes(String s) {
        
    }
}

```
![image](https://user-images.githubusercontent.com/60903744/120903237-a9e3eb80-c64d-11eb-86c1-220adf08fb11.png)

**Comment by ErdemT09** [comment]
The left side of the string is the backtracking part  (a, b, c are like 1 , 2, 3) and the right side of the string is just trying to copy/reflect it, if possible.
