### ISSUE TITLE
311. Sparse Matrix Multiplication

### ISSUE THREAD

**Issue by altayhunoglu** [spiralgo/algorithms#9]
Matrix, bir çok boyutlu array ( int[][]) olarak düşünülebilir.

Çoğunluk elemanı 0 olan matrixlere, "Sparse matrix" (seyrek matris) deniyor.

A ve B diye iki matrix veriliyor. Bu iki matrixin çarpılması isteniyor.
A'nın sütun sayısı, B'nin satır sayısına eşit.

Not: Bu soru için, Matris çarpımı ile ilgili matematik konusu kısaca araştırılmalıdır.

**Comment by ErdemT09** [comment]
Solved:
https://github.com/spiralgo/algorithms/tree/master/src/main/java/algorithms/curated170/medium/sparsematrixmultiplication
