### ISSUE TITLE
442. Find All Duplicates in an Array

### ISSUE THREAD

**Issue by ErdemT09** [spiralgo/algorithms#98]
Soru: Bize bir integer array'i veriliyor, bu array'de bazı ögeler 2 kez, bazılar 1 kez var. Array'deki sayıların değeri [1;array.length] aralığında. 
Bizden 2 kez çıkan sayıların listesi isteniyor.
Fazladan ise soruda bunu fazladan alan kullanmadan O(n)'de yapmamız isteniyor.

Çözüm: Bu soru pratikte genel bir duplicate bulmak sorusundan farklı. Bu soru, özellikle yazılım mülakatlarında mülakatçınnı talimatlarını ve verdiği bilgilerin sahip olabileceği önemi gösteriyor.
Eğer bu array'de her ögenin değeri o verilen aralıktaysa, o zaman (array[i]-1) değeri her zaman bir index'e karşılık gelecektir.
Mesela 1 4 2 3 4 array'ine bakalım.
1 değeri 0 index'ine bakar. 0 index'teki elementi negatif yapıyoruz.
4 değeri 3 index'ine bakar. 3 index'teki elementi negatif yapıyoruz.
2 değeri 1 index'ine bakar. 1 index'teki elementi negatif yapıyoruz.
3 değeri 2 index'ine bakar. 2 index'teki elementi negatif yapıyoruz.
=>  -1 -4 -2 -3 4
Burada sondaki 4, 3 index'ine bakacak. Eğer bu index'teki sayı negatifse, yani daha önce kendisiyle aynı index'e işaret eden aynı değerli bir sayı varmışsa, o zaman 4 sayısının mutlak değerini (4 mesela 3 index'inde olsaydı negatife dönüştürmüş olacaktık) döndürdüğümüz listeye ekliyoruz. 
Listeyi döndürüyoruz.
2. çözüm Hashset kullanmak, ama bu sorudaki constant space isteğini bozuyor.

Kod:
```
 public List<Integer> findDuplicates(int[] nums) {
            List<Integer> ret = new ArrayList();
        for(int i = 0; i<nums.length; i++)
        {
            int index = Math.abs(nums[i])-1;
            if(nums[index] < 0)
            {
                ret.add(index+1);
            }
            nums[index] = -nums[index];
        }
        return ret;
    }
```

**Comment by altayhunoglu** [comment]
Çok teşekkürler Erdem.
Şuradaki PR ile hallettik:
https://github.com/altayhunoglu/algorithms/pull/99

**Comment by altayhunoglu** [comment]
Bir sayıyı kendi negatifi ile işaretlemek, hem de bunu bir List<Integer> sâyesinde tek döngüde yapmak gayet zekice. Dolayısı ile ekleyebileceğim bir fikir yok.
  Kodu aynen alalım.
  Tebrikler :)

**Comment by ErdemT09** [comment]
Solved:
https://github.com/spiralgo/algorithms/blob/master/src/main/java/algorithms/medium/FindAllDuplicatesInAnArray.java
